// Code generated by ent, DO NOT EDIT.

package modifieroption

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the modifieroption type in the database.
	Label = "modifier_option"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldImageURL holds the string denoting the image_url field in the database.
	FieldImageURL = "image_url"
	// FieldAvailable holds the string denoting the available field in the database.
	FieldAvailable = "available"
	// FieldPreSelect holds the string denoting the pre_select field in the database.
	FieldPreSelect = "pre_select"
	// FieldModifierID holds the string denoting the modifier_id field in the database.
	FieldModifierID = "modifier_id"
	// EdgeModifier holds the string denoting the modifier edge name in mutations.
	EdgeModifier = "modifier"
	// Table holds the table name of the modifieroption in the database.
	Table = "modifier_options"
	// ModifierTable is the table that holds the modifier relation/edge.
	ModifierTable = "modifier_options"
	// ModifierInverseTable is the table name for the Modifier entity.
	// It exists in this package in order to avoid circular dependency with the "modifier" package.
	ModifierInverseTable = "modifiers"
	// ModifierColumn is the table column denoting the modifier relation/edge.
	ModifierColumn = "modifier_id"
)

// Columns holds all SQL columns for modifieroption fields.
var Columns = []string{
	FieldID,
	FieldUpdateTime,
	FieldName,
	FieldPrice,
	FieldImageURL,
	FieldAvailable,
	FieldPreSelect,
	FieldModifierID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultPrice holds the default value on creation for the "price" field.
	DefaultPrice float64
	// DefaultAvailable holds the default value on creation for the "available" field.
	DefaultAvailable bool
	// DefaultPreSelect holds the default value on creation for the "pre_select" field.
	DefaultPreSelect bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the ModifierOption queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByImageURL orders the results by the image_url field.
func ByImageURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageURL, opts...).ToFunc()
}

// ByAvailable orders the results by the available field.
func ByAvailable(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvailable, opts...).ToFunc()
}

// ByPreSelect orders the results by the pre_select field.
func ByPreSelect(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPreSelect, opts...).ToFunc()
}

// ByModifierID orders the results by the modifier_id field.
func ByModifierID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModifierID, opts...).ToFunc()
}

// ByModifierField orders the results by modifier field.
func ByModifierField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newModifierStep(), sql.OrderByField(field, opts...))
	}
}
func newModifierStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ModifierInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ModifierTable, ModifierColumn),
	)
}
