services:
  db:
    image: postgres:18.0
    container_name: rms_db
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rms_user -d rms_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
