// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/Jiruu246/rms/internal/ent/migrate"
	"github.com/google/uuid"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Jiruu246/rms/internal/ent/category"
	"github.com/Jiruu246/rms/internal/ent/menuitem"
	"github.com/Jiruu246/rms/internal/ent/modifier"
	"github.com/Jiruu246/rms/internal/ent/modifieroption"
	"github.com/Jiruu246/rms/internal/ent/restaurant"
	"github.com/Jiruu246/rms/internal/ent/user"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Category is the client for interacting with the Category builders.
	Category *CategoryClient
	// MenuItem is the client for interacting with the MenuItem builders.
	MenuItem *MenuItemClient
	// Modifier is the client for interacting with the Modifier builders.
	Modifier *ModifierClient
	// ModifierOption is the client for interacting with the ModifierOption builders.
	ModifierOption *ModifierOptionClient
	// Restaurant is the client for interacting with the Restaurant builders.
	Restaurant *RestaurantClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Category = NewCategoryClient(c.config)
	c.MenuItem = NewMenuItemClient(c.config)
	c.Modifier = NewModifierClient(c.config)
	c.ModifierOption = NewModifierOptionClient(c.config)
	c.Restaurant = NewRestaurantClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		Category:       NewCategoryClient(cfg),
		MenuItem:       NewMenuItemClient(cfg),
		Modifier:       NewModifierClient(cfg),
		ModifierOption: NewModifierOptionClient(cfg),
		Restaurant:     NewRestaurantClient(cfg),
		User:           NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		Category:       NewCategoryClient(cfg),
		MenuItem:       NewMenuItemClient(cfg),
		Modifier:       NewModifierClient(cfg),
		ModifierOption: NewModifierOptionClient(cfg),
		Restaurant:     NewRestaurantClient(cfg),
		User:           NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Category.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.Category, c.MenuItem, c.Modifier, c.ModifierOption, c.Restaurant, c.User,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.Category, c.MenuItem, c.Modifier, c.ModifierOption, c.Restaurant, c.User,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *CategoryMutation:
		return c.Category.mutate(ctx, m)
	case *MenuItemMutation:
		return c.MenuItem.mutate(ctx, m)
	case *ModifierMutation:
		return c.Modifier.mutate(ctx, m)
	case *ModifierOptionMutation:
		return c.ModifierOption.mutate(ctx, m)
	case *RestaurantMutation:
		return c.Restaurant.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// CategoryClient is a client for the Category schema.
type CategoryClient struct {
	config
}

// NewCategoryClient returns a client for the Category from the given config.
func NewCategoryClient(c config) *CategoryClient {
	return &CategoryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `category.Hooks(f(g(h())))`.
func (c *CategoryClient) Use(hooks ...Hook) {
	c.hooks.Category = append(c.hooks.Category, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `category.Intercept(f(g(h())))`.
func (c *CategoryClient) Intercept(interceptors ...Interceptor) {
	c.inters.Category = append(c.inters.Category, interceptors...)
}

// Create returns a builder for creating a Category entity.
func (c *CategoryClient) Create() *CategoryCreate {
	mutation := newCategoryMutation(c.config, OpCreate)
	return &CategoryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Category entities.
func (c *CategoryClient) CreateBulk(builders ...*CategoryCreate) *CategoryCreateBulk {
	return &CategoryCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CategoryClient) MapCreateBulk(slice any, setFunc func(*CategoryCreate, int)) *CategoryCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CategoryCreateBulk{err: fmt.Errorf("calling to CategoryClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CategoryCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CategoryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Category.
func (c *CategoryClient) Update() *CategoryUpdate {
	mutation := newCategoryMutation(c.config, OpUpdate)
	return &CategoryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CategoryClient) UpdateOne(_m *Category) *CategoryUpdateOne {
	mutation := newCategoryMutation(c.config, OpUpdateOne, withCategory(_m))
	return &CategoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CategoryClient) UpdateOneID(id uuid.UUID) *CategoryUpdateOne {
	mutation := newCategoryMutation(c.config, OpUpdateOne, withCategoryID(id))
	return &CategoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Category.
func (c *CategoryClient) Delete() *CategoryDelete {
	mutation := newCategoryMutation(c.config, OpDelete)
	return &CategoryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CategoryClient) DeleteOne(_m *Category) *CategoryDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CategoryClient) DeleteOneID(id uuid.UUID) *CategoryDeleteOne {
	builder := c.Delete().Where(category.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CategoryDeleteOne{builder}
}

// Query returns a query builder for Category.
func (c *CategoryClient) Query() *CategoryQuery {
	return &CategoryQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCategory},
		inters: c.Interceptors(),
	}
}

// Get returns a Category entity by its id.
func (c *CategoryClient) Get(ctx context.Context, id uuid.UUID) (*Category, error) {
	return c.Query().Where(category.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CategoryClient) GetX(ctx context.Context, id uuid.UUID) *Category {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRestaurant queries the restaurant edge of a Category.
func (c *CategoryClient) QueryRestaurant(_m *Category) *RestaurantQuery {
	query := (&RestaurantClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(category.Table, category.FieldID, id),
			sqlgraph.To(restaurant.Table, restaurant.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, category.RestaurantTable, category.RestaurantColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryMenuItems queries the menu_items edge of a Category.
func (c *CategoryClient) QueryMenuItems(_m *Category) *MenuItemQuery {
	query := (&MenuItemClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(category.Table, category.FieldID, id),
			sqlgraph.To(menuitem.Table, menuitem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, category.MenuItemsTable, category.MenuItemsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CategoryClient) Hooks() []Hook {
	return c.hooks.Category
}

// Interceptors returns the client interceptors.
func (c *CategoryClient) Interceptors() []Interceptor {
	return c.inters.Category
}

func (c *CategoryClient) mutate(ctx context.Context, m *CategoryMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CategoryCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CategoryUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CategoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CategoryDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Category mutation op: %q", m.Op())
	}
}

// MenuItemClient is a client for the MenuItem schema.
type MenuItemClient struct {
	config
}

// NewMenuItemClient returns a client for the MenuItem from the given config.
func NewMenuItemClient(c config) *MenuItemClient {
	return &MenuItemClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `menuitem.Hooks(f(g(h())))`.
func (c *MenuItemClient) Use(hooks ...Hook) {
	c.hooks.MenuItem = append(c.hooks.MenuItem, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `menuitem.Intercept(f(g(h())))`.
func (c *MenuItemClient) Intercept(interceptors ...Interceptor) {
	c.inters.MenuItem = append(c.inters.MenuItem, interceptors...)
}

// Create returns a builder for creating a MenuItem entity.
func (c *MenuItemClient) Create() *MenuItemCreate {
	mutation := newMenuItemMutation(c.config, OpCreate)
	return &MenuItemCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MenuItem entities.
func (c *MenuItemClient) CreateBulk(builders ...*MenuItemCreate) *MenuItemCreateBulk {
	return &MenuItemCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MenuItemClient) MapCreateBulk(slice any, setFunc func(*MenuItemCreate, int)) *MenuItemCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MenuItemCreateBulk{err: fmt.Errorf("calling to MenuItemClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MenuItemCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MenuItemCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MenuItem.
func (c *MenuItemClient) Update() *MenuItemUpdate {
	mutation := newMenuItemMutation(c.config, OpUpdate)
	return &MenuItemUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MenuItemClient) UpdateOne(_m *MenuItem) *MenuItemUpdateOne {
	mutation := newMenuItemMutation(c.config, OpUpdateOne, withMenuItem(_m))
	return &MenuItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MenuItemClient) UpdateOneID(id int64) *MenuItemUpdateOne {
	mutation := newMenuItemMutation(c.config, OpUpdateOne, withMenuItemID(id))
	return &MenuItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MenuItem.
func (c *MenuItemClient) Delete() *MenuItemDelete {
	mutation := newMenuItemMutation(c.config, OpDelete)
	return &MenuItemDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MenuItemClient) DeleteOne(_m *MenuItem) *MenuItemDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MenuItemClient) DeleteOneID(id int64) *MenuItemDeleteOne {
	builder := c.Delete().Where(menuitem.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MenuItemDeleteOne{builder}
}

// Query returns a query builder for MenuItem.
func (c *MenuItemClient) Query() *MenuItemQuery {
	return &MenuItemQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMenuItem},
		inters: c.Interceptors(),
	}
}

// Get returns a MenuItem entity by its id.
func (c *MenuItemClient) Get(ctx context.Context, id int64) (*MenuItem, error) {
	return c.Query().Where(menuitem.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MenuItemClient) GetX(ctx context.Context, id int64) *MenuItem {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRestaurant queries the restaurant edge of a MenuItem.
func (c *MenuItemClient) QueryRestaurant(_m *MenuItem) *RestaurantQuery {
	query := (&RestaurantClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(menuitem.Table, menuitem.FieldID, id),
			sqlgraph.To(restaurant.Table, restaurant.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, menuitem.RestaurantTable, menuitem.RestaurantColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCategory queries the category edge of a MenuItem.
func (c *MenuItemClient) QueryCategory(_m *MenuItem) *CategoryQuery {
	query := (&CategoryClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(menuitem.Table, menuitem.FieldID, id),
			sqlgraph.To(category.Table, category.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, menuitem.CategoryTable, menuitem.CategoryColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *MenuItemClient) Hooks() []Hook {
	return c.hooks.MenuItem
}

// Interceptors returns the client interceptors.
func (c *MenuItemClient) Interceptors() []Interceptor {
	return c.inters.MenuItem
}

func (c *MenuItemClient) mutate(ctx context.Context, m *MenuItemMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MenuItemCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MenuItemUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MenuItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MenuItemDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MenuItem mutation op: %q", m.Op())
	}
}

// ModifierClient is a client for the Modifier schema.
type ModifierClient struct {
	config
}

// NewModifierClient returns a client for the Modifier from the given config.
func NewModifierClient(c config) *ModifierClient {
	return &ModifierClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `modifier.Hooks(f(g(h())))`.
func (c *ModifierClient) Use(hooks ...Hook) {
	c.hooks.Modifier = append(c.hooks.Modifier, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `modifier.Intercept(f(g(h())))`.
func (c *ModifierClient) Intercept(interceptors ...Interceptor) {
	c.inters.Modifier = append(c.inters.Modifier, interceptors...)
}

// Create returns a builder for creating a Modifier entity.
func (c *ModifierClient) Create() *ModifierCreate {
	mutation := newModifierMutation(c.config, OpCreate)
	return &ModifierCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Modifier entities.
func (c *ModifierClient) CreateBulk(builders ...*ModifierCreate) *ModifierCreateBulk {
	return &ModifierCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ModifierClient) MapCreateBulk(slice any, setFunc func(*ModifierCreate, int)) *ModifierCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ModifierCreateBulk{err: fmt.Errorf("calling to ModifierClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ModifierCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ModifierCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Modifier.
func (c *ModifierClient) Update() *ModifierUpdate {
	mutation := newModifierMutation(c.config, OpUpdate)
	return &ModifierUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ModifierClient) UpdateOne(_m *Modifier) *ModifierUpdateOne {
	mutation := newModifierMutation(c.config, OpUpdateOne, withModifier(_m))
	return &ModifierUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ModifierClient) UpdateOneID(id uuid.UUID) *ModifierUpdateOne {
	mutation := newModifierMutation(c.config, OpUpdateOne, withModifierID(id))
	return &ModifierUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Modifier.
func (c *ModifierClient) Delete() *ModifierDelete {
	mutation := newModifierMutation(c.config, OpDelete)
	return &ModifierDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ModifierClient) DeleteOne(_m *Modifier) *ModifierDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ModifierClient) DeleteOneID(id uuid.UUID) *ModifierDeleteOne {
	builder := c.Delete().Where(modifier.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ModifierDeleteOne{builder}
}

// Query returns a query builder for Modifier.
func (c *ModifierClient) Query() *ModifierQuery {
	return &ModifierQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeModifier},
		inters: c.Interceptors(),
	}
}

// Get returns a Modifier entity by its id.
func (c *ModifierClient) Get(ctx context.Context, id uuid.UUID) (*Modifier, error) {
	return c.Query().Where(modifier.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ModifierClient) GetX(ctx context.Context, id uuid.UUID) *Modifier {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRestaurant queries the restaurant edge of a Modifier.
func (c *ModifierClient) QueryRestaurant(_m *Modifier) *RestaurantQuery {
	query := (&RestaurantClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(modifier.Table, modifier.FieldID, id),
			sqlgraph.To(restaurant.Table, restaurant.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, modifier.RestaurantTable, modifier.RestaurantColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryModifierOptions queries the modifier_options edge of a Modifier.
func (c *ModifierClient) QueryModifierOptions(_m *Modifier) *ModifierOptionQuery {
	query := (&ModifierOptionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(modifier.Table, modifier.FieldID, id),
			sqlgraph.To(modifieroption.Table, modifieroption.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, modifier.ModifierOptionsTable, modifier.ModifierOptionsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ModifierClient) Hooks() []Hook {
	return c.hooks.Modifier
}

// Interceptors returns the client interceptors.
func (c *ModifierClient) Interceptors() []Interceptor {
	return c.inters.Modifier
}

func (c *ModifierClient) mutate(ctx context.Context, m *ModifierMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ModifierCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ModifierUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ModifierUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ModifierDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Modifier mutation op: %q", m.Op())
	}
}

// ModifierOptionClient is a client for the ModifierOption schema.
type ModifierOptionClient struct {
	config
}

// NewModifierOptionClient returns a client for the ModifierOption from the given config.
func NewModifierOptionClient(c config) *ModifierOptionClient {
	return &ModifierOptionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `modifieroption.Hooks(f(g(h())))`.
func (c *ModifierOptionClient) Use(hooks ...Hook) {
	c.hooks.ModifierOption = append(c.hooks.ModifierOption, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `modifieroption.Intercept(f(g(h())))`.
func (c *ModifierOptionClient) Intercept(interceptors ...Interceptor) {
	c.inters.ModifierOption = append(c.inters.ModifierOption, interceptors...)
}

// Create returns a builder for creating a ModifierOption entity.
func (c *ModifierOptionClient) Create() *ModifierOptionCreate {
	mutation := newModifierOptionMutation(c.config, OpCreate)
	return &ModifierOptionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ModifierOption entities.
func (c *ModifierOptionClient) CreateBulk(builders ...*ModifierOptionCreate) *ModifierOptionCreateBulk {
	return &ModifierOptionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ModifierOptionClient) MapCreateBulk(slice any, setFunc func(*ModifierOptionCreate, int)) *ModifierOptionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ModifierOptionCreateBulk{err: fmt.Errorf("calling to ModifierOptionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ModifierOptionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ModifierOptionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ModifierOption.
func (c *ModifierOptionClient) Update() *ModifierOptionUpdate {
	mutation := newModifierOptionMutation(c.config, OpUpdate)
	return &ModifierOptionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ModifierOptionClient) UpdateOne(_m *ModifierOption) *ModifierOptionUpdateOne {
	mutation := newModifierOptionMutation(c.config, OpUpdateOne, withModifierOption(_m))
	return &ModifierOptionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ModifierOptionClient) UpdateOneID(id uuid.UUID) *ModifierOptionUpdateOne {
	mutation := newModifierOptionMutation(c.config, OpUpdateOne, withModifierOptionID(id))
	return &ModifierOptionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ModifierOption.
func (c *ModifierOptionClient) Delete() *ModifierOptionDelete {
	mutation := newModifierOptionMutation(c.config, OpDelete)
	return &ModifierOptionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ModifierOptionClient) DeleteOne(_m *ModifierOption) *ModifierOptionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ModifierOptionClient) DeleteOneID(id uuid.UUID) *ModifierOptionDeleteOne {
	builder := c.Delete().Where(modifieroption.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ModifierOptionDeleteOne{builder}
}

// Query returns a query builder for ModifierOption.
func (c *ModifierOptionClient) Query() *ModifierOptionQuery {
	return &ModifierOptionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeModifierOption},
		inters: c.Interceptors(),
	}
}

// Get returns a ModifierOption entity by its id.
func (c *ModifierOptionClient) Get(ctx context.Context, id uuid.UUID) (*ModifierOption, error) {
	return c.Query().Where(modifieroption.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ModifierOptionClient) GetX(ctx context.Context, id uuid.UUID) *ModifierOption {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryModifier queries the modifier edge of a ModifierOption.
func (c *ModifierOptionClient) QueryModifier(_m *ModifierOption) *ModifierQuery {
	query := (&ModifierClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(modifieroption.Table, modifieroption.FieldID, id),
			sqlgraph.To(modifier.Table, modifier.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, modifieroption.ModifierTable, modifieroption.ModifierColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ModifierOptionClient) Hooks() []Hook {
	return c.hooks.ModifierOption
}

// Interceptors returns the client interceptors.
func (c *ModifierOptionClient) Interceptors() []Interceptor {
	return c.inters.ModifierOption
}

func (c *ModifierOptionClient) mutate(ctx context.Context, m *ModifierOptionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ModifierOptionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ModifierOptionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ModifierOptionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ModifierOptionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ModifierOption mutation op: %q", m.Op())
	}
}

// RestaurantClient is a client for the Restaurant schema.
type RestaurantClient struct {
	config
}

// NewRestaurantClient returns a client for the Restaurant from the given config.
func NewRestaurantClient(c config) *RestaurantClient {
	return &RestaurantClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `restaurant.Hooks(f(g(h())))`.
func (c *RestaurantClient) Use(hooks ...Hook) {
	c.hooks.Restaurant = append(c.hooks.Restaurant, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `restaurant.Intercept(f(g(h())))`.
func (c *RestaurantClient) Intercept(interceptors ...Interceptor) {
	c.inters.Restaurant = append(c.inters.Restaurant, interceptors...)
}

// Create returns a builder for creating a Restaurant entity.
func (c *RestaurantClient) Create() *RestaurantCreate {
	mutation := newRestaurantMutation(c.config, OpCreate)
	return &RestaurantCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Restaurant entities.
func (c *RestaurantClient) CreateBulk(builders ...*RestaurantCreate) *RestaurantCreateBulk {
	return &RestaurantCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RestaurantClient) MapCreateBulk(slice any, setFunc func(*RestaurantCreate, int)) *RestaurantCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RestaurantCreateBulk{err: fmt.Errorf("calling to RestaurantClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RestaurantCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RestaurantCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Restaurant.
func (c *RestaurantClient) Update() *RestaurantUpdate {
	mutation := newRestaurantMutation(c.config, OpUpdate)
	return &RestaurantUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RestaurantClient) UpdateOne(_m *Restaurant) *RestaurantUpdateOne {
	mutation := newRestaurantMutation(c.config, OpUpdateOne, withRestaurant(_m))
	return &RestaurantUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RestaurantClient) UpdateOneID(id uuid.UUID) *RestaurantUpdateOne {
	mutation := newRestaurantMutation(c.config, OpUpdateOne, withRestaurantID(id))
	return &RestaurantUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Restaurant.
func (c *RestaurantClient) Delete() *RestaurantDelete {
	mutation := newRestaurantMutation(c.config, OpDelete)
	return &RestaurantDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RestaurantClient) DeleteOne(_m *Restaurant) *RestaurantDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RestaurantClient) DeleteOneID(id uuid.UUID) *RestaurantDeleteOne {
	builder := c.Delete().Where(restaurant.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RestaurantDeleteOne{builder}
}

// Query returns a query builder for Restaurant.
func (c *RestaurantClient) Query() *RestaurantQuery {
	return &RestaurantQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRestaurant},
		inters: c.Interceptors(),
	}
}

// Get returns a Restaurant entity by its id.
func (c *RestaurantClient) Get(ctx context.Context, id uuid.UUID) (*Restaurant, error) {
	return c.Query().Where(restaurant.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RestaurantClient) GetX(ctx context.Context, id uuid.UUID) *Restaurant {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a Restaurant.
func (c *RestaurantClient) QueryUser(_m *Restaurant) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(restaurant.Table, restaurant.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, restaurant.UserTable, restaurant.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryMenuItems queries the menu_items edge of a Restaurant.
func (c *RestaurantClient) QueryMenuItems(_m *Restaurant) *MenuItemQuery {
	query := (&MenuItemClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(restaurant.Table, restaurant.FieldID, id),
			sqlgraph.To(menuitem.Table, menuitem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, restaurant.MenuItemsTable, restaurant.MenuItemsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCategories queries the categories edge of a Restaurant.
func (c *RestaurantClient) QueryCategories(_m *Restaurant) *CategoryQuery {
	query := (&CategoryClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(restaurant.Table, restaurant.FieldID, id),
			sqlgraph.To(category.Table, category.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, restaurant.CategoriesTable, restaurant.CategoriesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryModifiers queries the modifiers edge of a Restaurant.
func (c *RestaurantClient) QueryModifiers(_m *Restaurant) *ModifierQuery {
	query := (&ModifierClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(restaurant.Table, restaurant.FieldID, id),
			sqlgraph.To(modifier.Table, modifier.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, restaurant.ModifiersTable, restaurant.ModifiersColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RestaurantClient) Hooks() []Hook {
	return c.hooks.Restaurant
}

// Interceptors returns the client interceptors.
func (c *RestaurantClient) Interceptors() []Interceptor {
	return c.inters.Restaurant
}

func (c *RestaurantClient) mutate(ctx context.Context, m *RestaurantMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RestaurantCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RestaurantUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RestaurantUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RestaurantDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Restaurant mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(_m))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id uuid.UUID) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id uuid.UUID) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id uuid.UUID) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id uuid.UUID) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRestaurants queries the restaurants edge of a User.
func (c *UserClient) QueryRestaurants(_m *User) *RestaurantQuery {
	query := (&RestaurantClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(restaurant.Table, restaurant.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.RestaurantsTable, user.RestaurantsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Category, MenuItem, Modifier, ModifierOption, Restaurant, User []ent.Hook
	}
	inters struct {
		Category, MenuItem, Modifier, ModifierOption, Restaurant, User []ent.Interceptor
	}
)
