// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Jiruu246/rms/internal/ent/mediaasset"
	"github.com/Jiruu246/rms/internal/ent/mediaupload"
	"github.com/Jiruu246/rms/internal/ent/user"
	"github.com/google/uuid"
)

// MediaUploadCreate is the builder for creating a MediaUpload entity.
type MediaUploadCreate struct {
	config
	mutation *MediaUploadMutation
	hooks    []Hook
}

// SetUpdateTime sets the "update_time" field.
func (_c *MediaUploadCreate) SetUpdateTime(v time.Time) *MediaUploadCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *MediaUploadCreate) SetNillableUpdateTime(v *time.Time) *MediaUploadCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *MediaUploadCreate) SetCreateTime(v time.Time) *MediaUploadCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *MediaUploadCreate) SetNillableCreateTime(v *time.Time) *MediaUploadCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetOwnerID sets the "owner_id" field.
func (_c *MediaUploadCreate) SetOwnerID(v uuid.UUID) *MediaUploadCreate {
	_c.mutation.SetOwnerID(v)
	return _c
}

// SetPurpose sets the "purpose" field.
func (_c *MediaUploadCreate) SetPurpose(v mediaupload.Purpose) *MediaUploadCreate {
	_c.mutation.SetPurpose(v)
	return _c
}

// SetObjectKey sets the "object_key" field.
func (_c *MediaUploadCreate) SetObjectKey(v string) *MediaUploadCreate {
	_c.mutation.SetObjectKey(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *MediaUploadCreate) SetStatus(v mediaupload.Status) *MediaUploadCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *MediaUploadCreate) SetNillableStatus(v *mediaupload.Status) *MediaUploadCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *MediaUploadCreate) SetExpiresAt(v time.Time) *MediaUploadCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *MediaUploadCreate) SetID(v uuid.UUID) *MediaUploadCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MediaUploadCreate) SetNillableID(v *uuid.UUID) *MediaUploadCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *MediaUploadCreate) SetOwner(v *User) *MediaUploadCreate {
	return _c.SetOwnerID(v.ID)
}

// SetAssetID sets the "asset" edge to the MediaAsset entity by ID.
func (_c *MediaUploadCreate) SetAssetID(id uuid.UUID) *MediaUploadCreate {
	_c.mutation.SetAssetID(id)
	return _c
}

// SetNillableAssetID sets the "asset" edge to the MediaAsset entity by ID if the given value is not nil.
func (_c *MediaUploadCreate) SetNillableAssetID(id *uuid.UUID) *MediaUploadCreate {
	if id != nil {
		_c = _c.SetAssetID(*id)
	}
	return _c
}

// SetAsset sets the "asset" edge to the MediaAsset entity.
func (_c *MediaUploadCreate) SetAsset(v *MediaAsset) *MediaUploadCreate {
	return _c.SetAssetID(v.ID)
}

// Mutation returns the MediaUploadMutation object of the builder.
func (_c *MediaUploadCreate) Mutation() *MediaUploadMutation {
	return _c.mutation
}

// Save creates the MediaUpload in the database.
func (_c *MediaUploadCreate) Save(ctx context.Context) (*MediaUpload, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MediaUploadCreate) SaveX(ctx context.Context) *MediaUpload {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MediaUploadCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MediaUploadCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MediaUploadCreate) defaults() {
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := mediaupload.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := mediaupload.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := mediaupload.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := mediaupload.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MediaUploadCreate) check() error {
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "MediaUpload.update_time"`)}
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "MediaUpload.create_time"`)}
	}
	if _, ok := _c.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner_id", err: errors.New(`ent: missing required field "MediaUpload.owner_id"`)}
	}
	if _, ok := _c.mutation.Purpose(); !ok {
		return &ValidationError{Name: "purpose", err: errors.New(`ent: missing required field "MediaUpload.purpose"`)}
	}
	if v, ok := _c.mutation.Purpose(); ok {
		if err := mediaupload.PurposeValidator(v); err != nil {
			return &ValidationError{Name: "purpose", err: fmt.Errorf(`ent: validator failed for field "MediaUpload.purpose": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ObjectKey(); !ok {
		return &ValidationError{Name: "object_key", err: errors.New(`ent: missing required field "MediaUpload.object_key"`)}
	}
	if v, ok := _c.mutation.ObjectKey(); ok {
		if err := mediaupload.ObjectKeyValidator(v); err != nil {
			return &ValidationError{Name: "object_key", err: fmt.Errorf(`ent: validator failed for field "MediaUpload.object_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "MediaUpload.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := mediaupload.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MediaUpload.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "MediaUpload.expires_at"`)}
	}
	if len(_c.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "MediaUpload.owner"`)}
	}
	return nil
}

func (_c *MediaUploadCreate) sqlSave(ctx context.Context) (*MediaUpload, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MediaUploadCreate) createSpec() (*MediaUpload, *sqlgraph.CreateSpec) {
	var (
		_node = &MediaUpload{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mediaupload.Table, sqlgraph.NewFieldSpec(mediaupload.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(mediaupload.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(mediaupload.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.Purpose(); ok {
		_spec.SetField(mediaupload.FieldPurpose, field.TypeEnum, value)
		_node.Purpose = value
	}
	if value, ok := _c.mutation.ObjectKey(); ok {
		_spec.SetField(mediaupload.FieldObjectKey, field.TypeString, value)
		_node.ObjectKey = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(mediaupload.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(mediaupload.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaupload.OwnerTable,
			Columns: []string{mediaupload.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OwnerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AssetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   mediaupload.AssetTable,
			Columns: []string{mediaupload.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaasset.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MediaUploadCreateBulk is the builder for creating many MediaUpload entities in bulk.
type MediaUploadCreateBulk struct {
	config
	err      error
	builders []*MediaUploadCreate
}

// Save creates the MediaUpload entities in the database.
func (_c *MediaUploadCreateBulk) Save(ctx context.Context) ([]*MediaUpload, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MediaUpload, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MediaUploadMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MediaUploadCreateBulk) SaveX(ctx context.Context) []*MediaUpload {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MediaUploadCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MediaUploadCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
