// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Jiruu246/rms/internal/ent/mediaasset"
	"github.com/Jiruu246/rms/internal/ent/predicate"
)

// MediaAssetUpdate is the builder for updating MediaAsset entities.
type MediaAssetUpdate struct {
	config
	hooks    []Hook
	mutation *MediaAssetMutation
}

// Where appends a list predicates to the MediaAssetUpdate builder.
func (_u *MediaAssetUpdate) Where(ps ...predicate.MediaAsset) *MediaAssetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *MediaAssetUpdate) SetUpdateTime(v time.Time) *MediaAssetUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *MediaAssetUpdate) SetStatus(v mediaasset.Status) *MediaAssetUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MediaAssetUpdate) SetNillableStatus(v *mediaasset.Status) *MediaAssetUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// Mutation returns the MediaAssetMutation object of the builder.
func (_u *MediaAssetUpdate) Mutation() *MediaAssetMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MediaAssetUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaAssetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MediaAssetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaAssetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MediaAssetUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := mediaasset.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaAssetUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := mediaasset.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.status": %w`, err)}
		}
	}
	if _u.mutation.UploadedByCleared() && len(_u.mutation.UploadedByIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MediaAsset.uploaded_by"`)
	}
	if _u.mutation.UploadCleared() && len(_u.mutation.UploadIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MediaAsset.upload"`)
	}
	return nil
}

func (_u *MediaAssetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediaasset.Table, mediaasset.Columns, sqlgraph.NewFieldSpec(mediaasset.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(mediaasset.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(mediaasset.FieldStatus, field.TypeEnum, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediaasset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MediaAssetUpdateOne is the builder for updating a single MediaAsset entity.
type MediaAssetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MediaAssetMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *MediaAssetUpdateOne) SetUpdateTime(v time.Time) *MediaAssetUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *MediaAssetUpdateOne) SetStatus(v mediaasset.Status) *MediaAssetUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MediaAssetUpdateOne) SetNillableStatus(v *mediaasset.Status) *MediaAssetUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// Mutation returns the MediaAssetMutation object of the builder.
func (_u *MediaAssetUpdateOne) Mutation() *MediaAssetMutation {
	return _u.mutation
}

// Where appends a list predicates to the MediaAssetUpdate builder.
func (_u *MediaAssetUpdateOne) Where(ps ...predicate.MediaAsset) *MediaAssetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MediaAssetUpdateOne) Select(field string, fields ...string) *MediaAssetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MediaAsset entity.
func (_u *MediaAssetUpdateOne) Save(ctx context.Context) (*MediaAsset, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaAssetUpdateOne) SaveX(ctx context.Context) *MediaAsset {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MediaAssetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaAssetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MediaAssetUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := mediaasset.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaAssetUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := mediaasset.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.status": %w`, err)}
		}
	}
	if _u.mutation.UploadedByCleared() && len(_u.mutation.UploadedByIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MediaAsset.uploaded_by"`)
	}
	if _u.mutation.UploadCleared() && len(_u.mutation.UploadIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MediaAsset.upload"`)
	}
	return nil
}

func (_u *MediaAssetUpdateOne) sqlSave(ctx context.Context) (_node *MediaAsset, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediaasset.Table, mediaasset.Columns, sqlgraph.NewFieldSpec(mediaasset.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MediaAsset.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mediaasset.FieldID)
		for _, f := range fields {
			if !mediaasset.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mediaasset.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(mediaasset.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(mediaasset.FieldStatus, field.TypeEnum, value)
	}
	_node = &MediaAsset{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediaasset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
