// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Jiruu246/rms/internal/ent/mediaasset"
	"github.com/Jiruu246/rms/internal/ent/mediaupload"
	"github.com/Jiruu246/rms/internal/ent/user"
	"github.com/google/uuid"
)

// MediaAssetCreate is the builder for creating a MediaAsset entity.
type MediaAssetCreate struct {
	config
	mutation *MediaAssetMutation
	hooks    []Hook
}

// SetUpdateTime sets the "update_time" field.
func (_c *MediaAssetCreate) SetUpdateTime(v time.Time) *MediaAssetCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *MediaAssetCreate) SetNillableUpdateTime(v *time.Time) *MediaAssetCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *MediaAssetCreate) SetCreateTime(v time.Time) *MediaAssetCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *MediaAssetCreate) SetNillableCreateTime(v *time.Time) *MediaAssetCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUploadedByUserID sets the "uploaded_by_user_id" field.
func (_c *MediaAssetCreate) SetUploadedByUserID(v uuid.UUID) *MediaAssetCreate {
	_c.mutation.SetUploadedByUserID(v)
	return _c
}

// SetUploadID sets the "upload_id" field.
func (_c *MediaAssetCreate) SetUploadID(v uuid.UUID) *MediaAssetCreate {
	_c.mutation.SetUploadID(v)
	return _c
}

// SetStorageKey sets the "storage_key" field.
func (_c *MediaAssetCreate) SetStorageKey(v string) *MediaAssetCreate {
	_c.mutation.SetStorageKey(v)
	return _c
}

// SetContentType sets the "content_type" field.
func (_c *MediaAssetCreate) SetContentType(v string) *MediaAssetCreate {
	_c.mutation.SetContentType(v)
	return _c
}

// SetSizeBytes sets the "size_bytes" field.
func (_c *MediaAssetCreate) SetSizeBytes(v int64) *MediaAssetCreate {
	_c.mutation.SetSizeBytes(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *MediaAssetCreate) SetStatus(v mediaasset.Status) *MediaAssetCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *MediaAssetCreate) SetNillableStatus(v *mediaasset.Status) *MediaAssetCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MediaAssetCreate) SetID(v uuid.UUID) *MediaAssetCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MediaAssetCreate) SetNillableID(v *uuid.UUID) *MediaAssetCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUploadedByID sets the "uploaded_by" edge to the User entity by ID.
func (_c *MediaAssetCreate) SetUploadedByID(id uuid.UUID) *MediaAssetCreate {
	_c.mutation.SetUploadedByID(id)
	return _c
}

// SetUploadedBy sets the "uploaded_by" edge to the User entity.
func (_c *MediaAssetCreate) SetUploadedBy(v *User) *MediaAssetCreate {
	return _c.SetUploadedByID(v.ID)
}

// SetUpload sets the "upload" edge to the MediaUpload entity.
func (_c *MediaAssetCreate) SetUpload(v *MediaUpload) *MediaAssetCreate {
	return _c.SetUploadID(v.ID)
}

// Mutation returns the MediaAssetMutation object of the builder.
func (_c *MediaAssetCreate) Mutation() *MediaAssetMutation {
	return _c.mutation
}

// Save creates the MediaAsset in the database.
func (_c *MediaAssetCreate) Save(ctx context.Context) (*MediaAsset, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MediaAssetCreate) SaveX(ctx context.Context) *MediaAsset {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MediaAssetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MediaAssetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MediaAssetCreate) defaults() {
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := mediaasset.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := mediaasset.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := mediaasset.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := mediaasset.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MediaAssetCreate) check() error {
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "MediaAsset.update_time"`)}
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "MediaAsset.create_time"`)}
	}
	if _, ok := _c.mutation.UploadedByUserID(); !ok {
		return &ValidationError{Name: "uploaded_by_user_id", err: errors.New(`ent: missing required field "MediaAsset.uploaded_by_user_id"`)}
	}
	if _, ok := _c.mutation.UploadID(); !ok {
		return &ValidationError{Name: "upload_id", err: errors.New(`ent: missing required field "MediaAsset.upload_id"`)}
	}
	if _, ok := _c.mutation.StorageKey(); !ok {
		return &ValidationError{Name: "storage_key", err: errors.New(`ent: missing required field "MediaAsset.storage_key"`)}
	}
	if v, ok := _c.mutation.StorageKey(); ok {
		if err := mediaasset.StorageKeyValidator(v); err != nil {
			return &ValidationError{Name: "storage_key", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.storage_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContentType(); !ok {
		return &ValidationError{Name: "content_type", err: errors.New(`ent: missing required field "MediaAsset.content_type"`)}
	}
	if v, ok := _c.mutation.ContentType(); ok {
		if err := mediaasset.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.content_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SizeBytes(); !ok {
		return &ValidationError{Name: "size_bytes", err: errors.New(`ent: missing required field "MediaAsset.size_bytes"`)}
	}
	if v, ok := _c.mutation.SizeBytes(); ok {
		if err := mediaasset.SizeBytesValidator(v); err != nil {
			return &ValidationError{Name: "size_bytes", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.size_bytes": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "MediaAsset.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := mediaasset.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.status": %w`, err)}
		}
	}
	if len(_c.mutation.UploadedByIDs()) == 0 {
		return &ValidationError{Name: "uploaded_by", err: errors.New(`ent: missing required edge "MediaAsset.uploaded_by"`)}
	}
	if len(_c.mutation.UploadIDs()) == 0 {
		return &ValidationError{Name: "upload", err: errors.New(`ent: missing required edge "MediaAsset.upload"`)}
	}
	return nil
}

func (_c *MediaAssetCreate) sqlSave(ctx context.Context) (*MediaAsset, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MediaAssetCreate) createSpec() (*MediaAsset, *sqlgraph.CreateSpec) {
	var (
		_node = &MediaAsset{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mediaasset.Table, sqlgraph.NewFieldSpec(mediaasset.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(mediaasset.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(mediaasset.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.StorageKey(); ok {
		_spec.SetField(mediaasset.FieldStorageKey, field.TypeString, value)
		_node.StorageKey = value
	}
	if value, ok := _c.mutation.ContentType(); ok {
		_spec.SetField(mediaasset.FieldContentType, field.TypeString, value)
		_node.ContentType = value
	}
	if value, ok := _c.mutation.SizeBytes(); ok {
		_spec.SetField(mediaasset.FieldSizeBytes, field.TypeInt64, value)
		_node.SizeBytes = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(mediaasset.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if nodes := _c.mutation.UploadedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaasset.UploadedByTable,
			Columns: []string{mediaasset.UploadedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UploadedByUserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UploadIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   mediaasset.UploadTable,
			Columns: []string{mediaasset.UploadColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaupload.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UploadID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MediaAssetCreateBulk is the builder for creating many MediaAsset entities in bulk.
type MediaAssetCreateBulk struct {
	config
	err      error
	builders []*MediaAssetCreate
}

// Save creates the MediaAsset entities in the database.
func (_c *MediaAssetCreateBulk) Save(ctx context.Context) ([]*MediaAsset, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MediaAsset, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MediaAssetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MediaAssetCreateBulk) SaveX(ctx context.Context) []*MediaAsset {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MediaAssetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MediaAssetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
