// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Jiruu246/rms/internal/ent/modifier"
	"github.com/Jiruu246/rms/internal/ent/modifieroption"
	"github.com/Jiruu246/rms/internal/ent/predicate"
	"github.com/Jiruu246/rms/internal/ent/restaurant"
	"github.com/google/uuid"
)

// ModifierUpdate is the builder for updating Modifier entities.
type ModifierUpdate struct {
	config
	hooks    []Hook
	mutation *ModifierMutation
}

// Where appends a list predicates to the ModifierUpdate builder.
func (_u *ModifierUpdate) Where(ps ...predicate.Modifier) *ModifierUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *ModifierUpdate) SetUpdateTime(v time.Time) *ModifierUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ModifierUpdate) SetName(v string) *ModifierUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ModifierUpdate) SetNillableName(v *string) *ModifierUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRequired sets the "required" field.
func (_u *ModifierUpdate) SetRequired(v bool) *ModifierUpdate {
	_u.mutation.SetRequired(v)
	return _u
}

// SetNillableRequired sets the "required" field if the given value is not nil.
func (_u *ModifierUpdate) SetNillableRequired(v *bool) *ModifierUpdate {
	if v != nil {
		_u.SetRequired(*v)
	}
	return _u
}

// SetMultiSelect sets the "multi_select" field.
func (_u *ModifierUpdate) SetMultiSelect(v bool) *ModifierUpdate {
	_u.mutation.SetMultiSelect(v)
	return _u
}

// SetNillableMultiSelect sets the "multi_select" field if the given value is not nil.
func (_u *ModifierUpdate) SetNillableMultiSelect(v *bool) *ModifierUpdate {
	if v != nil {
		_u.SetMultiSelect(*v)
	}
	return _u
}

// SetMax sets the "max" field.
func (_u *ModifierUpdate) SetMax(v int) *ModifierUpdate {
	_u.mutation.ResetMax()
	_u.mutation.SetMax(v)
	return _u
}

// SetNillableMax sets the "max" field if the given value is not nil.
func (_u *ModifierUpdate) SetNillableMax(v *int) *ModifierUpdate {
	if v != nil {
		_u.SetMax(*v)
	}
	return _u
}

// AddMax adds value to the "max" field.
func (_u *ModifierUpdate) AddMax(v int) *ModifierUpdate {
	_u.mutation.AddMax(v)
	return _u
}

// SetRestaurantID sets the "restaurant_id" field.
func (_u *ModifierUpdate) SetRestaurantID(v uuid.UUID) *ModifierUpdate {
	_u.mutation.SetRestaurantID(v)
	return _u
}

// SetNillableRestaurantID sets the "restaurant_id" field if the given value is not nil.
func (_u *ModifierUpdate) SetNillableRestaurantID(v *uuid.UUID) *ModifierUpdate {
	if v != nil {
		_u.SetRestaurantID(*v)
	}
	return _u
}

// SetRestaurant sets the "restaurant" edge to the Restaurant entity.
func (_u *ModifierUpdate) SetRestaurant(v *Restaurant) *ModifierUpdate {
	return _u.SetRestaurantID(v.ID)
}

// AddModifierOptionIDs adds the "modifier_options" edge to the ModifierOption entity by IDs.
func (_u *ModifierUpdate) AddModifierOptionIDs(ids ...uuid.UUID) *ModifierUpdate {
	_u.mutation.AddModifierOptionIDs(ids...)
	return _u
}

// AddModifierOptions adds the "modifier_options" edges to the ModifierOption entity.
func (_u *ModifierUpdate) AddModifierOptions(v ...*ModifierOption) *ModifierUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddModifierOptionIDs(ids...)
}

// Mutation returns the ModifierMutation object of the builder.
func (_u *ModifierUpdate) Mutation() *ModifierMutation {
	return _u.mutation
}

// ClearRestaurant clears the "restaurant" edge to the Restaurant entity.
func (_u *ModifierUpdate) ClearRestaurant() *ModifierUpdate {
	_u.mutation.ClearRestaurant()
	return _u
}

// ClearModifierOptions clears all "modifier_options" edges to the ModifierOption entity.
func (_u *ModifierUpdate) ClearModifierOptions() *ModifierUpdate {
	_u.mutation.ClearModifierOptions()
	return _u
}

// RemoveModifierOptionIDs removes the "modifier_options" edge to ModifierOption entities by IDs.
func (_u *ModifierUpdate) RemoveModifierOptionIDs(ids ...uuid.UUID) *ModifierUpdate {
	_u.mutation.RemoveModifierOptionIDs(ids...)
	return _u
}

// RemoveModifierOptions removes "modifier_options" edges to ModifierOption entities.
func (_u *ModifierUpdate) RemoveModifierOptions(v ...*ModifierOption) *ModifierUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveModifierOptionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModifierUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModifierUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModifierUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModifierUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModifierUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := modifier.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModifierUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := modifier.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Modifier.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Max(); ok {
		if err := modifier.MaxValidator(v); err != nil {
			return &ValidationError{Name: "max", err: fmt.Errorf(`ent: validator failed for field "Modifier.max": %w`, err)}
		}
	}
	if _u.mutation.RestaurantCleared() && len(_u.mutation.RestaurantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Modifier.restaurant"`)
	}
	return nil
}

func (_u *ModifierUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modifier.Table, modifier.Columns, sqlgraph.NewFieldSpec(modifier.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(modifier.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(modifier.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Required(); ok {
		_spec.SetField(modifier.FieldRequired, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MultiSelect(); ok {
		_spec.SetField(modifier.FieldMultiSelect, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Max(); ok {
		_spec.SetField(modifier.FieldMax, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMax(); ok {
		_spec.AddField(modifier.FieldMax, field.TypeInt, value)
	}
	if _u.mutation.RestaurantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   modifier.RestaurantTable,
			Columns: []string{modifier.RestaurantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(restaurant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RestaurantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   modifier.RestaurantTable,
			Columns: []string{modifier.RestaurantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(restaurant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ModifierOptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modifier.ModifierOptionsTable,
			Columns: []string{modifier.ModifierOptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modifieroption.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedModifierOptionsIDs(); len(nodes) > 0 && !_u.mutation.ModifierOptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modifier.ModifierOptionsTable,
			Columns: []string{modifier.ModifierOptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modifieroption.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ModifierOptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modifier.ModifierOptionsTable,
			Columns: []string{modifier.ModifierOptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modifieroption.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modifier.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModifierUpdateOne is the builder for updating a single Modifier entity.
type ModifierUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModifierMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *ModifierUpdateOne) SetUpdateTime(v time.Time) *ModifierUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ModifierUpdateOne) SetName(v string) *ModifierUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ModifierUpdateOne) SetNillableName(v *string) *ModifierUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRequired sets the "required" field.
func (_u *ModifierUpdateOne) SetRequired(v bool) *ModifierUpdateOne {
	_u.mutation.SetRequired(v)
	return _u
}

// SetNillableRequired sets the "required" field if the given value is not nil.
func (_u *ModifierUpdateOne) SetNillableRequired(v *bool) *ModifierUpdateOne {
	if v != nil {
		_u.SetRequired(*v)
	}
	return _u
}

// SetMultiSelect sets the "multi_select" field.
func (_u *ModifierUpdateOne) SetMultiSelect(v bool) *ModifierUpdateOne {
	_u.mutation.SetMultiSelect(v)
	return _u
}

// SetNillableMultiSelect sets the "multi_select" field if the given value is not nil.
func (_u *ModifierUpdateOne) SetNillableMultiSelect(v *bool) *ModifierUpdateOne {
	if v != nil {
		_u.SetMultiSelect(*v)
	}
	return _u
}

// SetMax sets the "max" field.
func (_u *ModifierUpdateOne) SetMax(v int) *ModifierUpdateOne {
	_u.mutation.ResetMax()
	_u.mutation.SetMax(v)
	return _u
}

// SetNillableMax sets the "max" field if the given value is not nil.
func (_u *ModifierUpdateOne) SetNillableMax(v *int) *ModifierUpdateOne {
	if v != nil {
		_u.SetMax(*v)
	}
	return _u
}

// AddMax adds value to the "max" field.
func (_u *ModifierUpdateOne) AddMax(v int) *ModifierUpdateOne {
	_u.mutation.AddMax(v)
	return _u
}

// SetRestaurantID sets the "restaurant_id" field.
func (_u *ModifierUpdateOne) SetRestaurantID(v uuid.UUID) *ModifierUpdateOne {
	_u.mutation.SetRestaurantID(v)
	return _u
}

// SetNillableRestaurantID sets the "restaurant_id" field if the given value is not nil.
func (_u *ModifierUpdateOne) SetNillableRestaurantID(v *uuid.UUID) *ModifierUpdateOne {
	if v != nil {
		_u.SetRestaurantID(*v)
	}
	return _u
}

// SetRestaurant sets the "restaurant" edge to the Restaurant entity.
func (_u *ModifierUpdateOne) SetRestaurant(v *Restaurant) *ModifierUpdateOne {
	return _u.SetRestaurantID(v.ID)
}

// AddModifierOptionIDs adds the "modifier_options" edge to the ModifierOption entity by IDs.
func (_u *ModifierUpdateOne) AddModifierOptionIDs(ids ...uuid.UUID) *ModifierUpdateOne {
	_u.mutation.AddModifierOptionIDs(ids...)
	return _u
}

// AddModifierOptions adds the "modifier_options" edges to the ModifierOption entity.
func (_u *ModifierUpdateOne) AddModifierOptions(v ...*ModifierOption) *ModifierUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddModifierOptionIDs(ids...)
}

// Mutation returns the ModifierMutation object of the builder.
func (_u *ModifierUpdateOne) Mutation() *ModifierMutation {
	return _u.mutation
}

// ClearRestaurant clears the "restaurant" edge to the Restaurant entity.
func (_u *ModifierUpdateOne) ClearRestaurant() *ModifierUpdateOne {
	_u.mutation.ClearRestaurant()
	return _u
}

// ClearModifierOptions clears all "modifier_options" edges to the ModifierOption entity.
func (_u *ModifierUpdateOne) ClearModifierOptions() *ModifierUpdateOne {
	_u.mutation.ClearModifierOptions()
	return _u
}

// RemoveModifierOptionIDs removes the "modifier_options" edge to ModifierOption entities by IDs.
func (_u *ModifierUpdateOne) RemoveModifierOptionIDs(ids ...uuid.UUID) *ModifierUpdateOne {
	_u.mutation.RemoveModifierOptionIDs(ids...)
	return _u
}

// RemoveModifierOptions removes "modifier_options" edges to ModifierOption entities.
func (_u *ModifierUpdateOne) RemoveModifierOptions(v ...*ModifierOption) *ModifierUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveModifierOptionIDs(ids...)
}

// Where appends a list predicates to the ModifierUpdate builder.
func (_u *ModifierUpdateOne) Where(ps ...predicate.Modifier) *ModifierUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModifierUpdateOne) Select(field string, fields ...string) *ModifierUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Modifier entity.
func (_u *ModifierUpdateOne) Save(ctx context.Context) (*Modifier, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModifierUpdateOne) SaveX(ctx context.Context) *Modifier {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModifierUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModifierUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModifierUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := modifier.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModifierUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := modifier.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Modifier.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Max(); ok {
		if err := modifier.MaxValidator(v); err != nil {
			return &ValidationError{Name: "max", err: fmt.Errorf(`ent: validator failed for field "Modifier.max": %w`, err)}
		}
	}
	if _u.mutation.RestaurantCleared() && len(_u.mutation.RestaurantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Modifier.restaurant"`)
	}
	return nil
}

func (_u *ModifierUpdateOne) sqlSave(ctx context.Context) (_node *Modifier, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modifier.Table, modifier.Columns, sqlgraph.NewFieldSpec(modifier.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Modifier.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modifier.FieldID)
		for _, f := range fields {
			if !modifier.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != modifier.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(modifier.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(modifier.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Required(); ok {
		_spec.SetField(modifier.FieldRequired, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MultiSelect(); ok {
		_spec.SetField(modifier.FieldMultiSelect, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Max(); ok {
		_spec.SetField(modifier.FieldMax, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMax(); ok {
		_spec.AddField(modifier.FieldMax, field.TypeInt, value)
	}
	if _u.mutation.RestaurantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   modifier.RestaurantTable,
			Columns: []string{modifier.RestaurantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(restaurant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RestaurantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   modifier.RestaurantTable,
			Columns: []string{modifier.RestaurantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(restaurant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ModifierOptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modifier.ModifierOptionsTable,
			Columns: []string{modifier.ModifierOptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modifieroption.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedModifierOptionsIDs(); len(nodes) > 0 && !_u.mutation.ModifierOptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modifier.ModifierOptionsTable,
			Columns: []string{modifier.ModifierOptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modifieroption.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ModifierOptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modifier.ModifierOptionsTable,
			Columns: []string{modifier.ModifierOptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modifieroption.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Modifier{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modifier.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
