// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Jiruu246/rms/internal/ent/modifieroption"
	"github.com/Jiruu246/rms/internal/ent/orderitem"
	"github.com/Jiruu246/rms/internal/ent/orderitemmodifieroption"
	"github.com/Jiruu246/rms/internal/ent/predicate"
	"github.com/google/uuid"
)

// OrderItemModifierOptionUpdate is the builder for updating OrderItemModifierOption entities.
type OrderItemModifierOptionUpdate struct {
	config
	hooks    []Hook
	mutation *OrderItemModifierOptionMutation
}

// Where appends a list predicates to the OrderItemModifierOptionUpdate builder.
func (_u *OrderItemModifierOptionUpdate) Where(ps ...predicate.OrderItemModifierOption) *OrderItemModifierOptionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrderItemID sets the "order_item_id" field.
func (_u *OrderItemModifierOptionUpdate) SetOrderItemID(v uuid.UUID) *OrderItemModifierOptionUpdate {
	_u.mutation.SetOrderItemID(v)
	return _u
}

// SetNillableOrderItemID sets the "order_item_id" field if the given value is not nil.
func (_u *OrderItemModifierOptionUpdate) SetNillableOrderItemID(v *uuid.UUID) *OrderItemModifierOptionUpdate {
	if v != nil {
		_u.SetOrderItemID(*v)
	}
	return _u
}

// SetModifierOptionID sets the "modifier_option_id" field.
func (_u *OrderItemModifierOptionUpdate) SetModifierOptionID(v uuid.UUID) *OrderItemModifierOptionUpdate {
	_u.mutation.SetModifierOptionID(v)
	return _u
}

// SetNillableModifierOptionID sets the "modifier_option_id" field if the given value is not nil.
func (_u *OrderItemModifierOptionUpdate) SetNillableModifierOptionID(v *uuid.UUID) *OrderItemModifierOptionUpdate {
	if v != nil {
		_u.SetModifierOptionID(*v)
	}
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *OrderItemModifierOptionUpdate) SetQuantity(v int) *OrderItemModifierOptionUpdate {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *OrderItemModifierOptionUpdate) SetNillableQuantity(v *int) *OrderItemModifierOptionUpdate {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *OrderItemModifierOptionUpdate) AddQuantity(v int) *OrderItemModifierOptionUpdate {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetOptionName sets the "option_name" field.
func (_u *OrderItemModifierOptionUpdate) SetOptionName(v string) *OrderItemModifierOptionUpdate {
	_u.mutation.SetOptionName(v)
	return _u
}

// SetNillableOptionName sets the "option_name" field if the given value is not nil.
func (_u *OrderItemModifierOptionUpdate) SetNillableOptionName(v *string) *OrderItemModifierOptionUpdate {
	if v != nil {
		_u.SetOptionName(*v)
	}
	return _u
}

// SetOptionPrice sets the "option_price" field.
func (_u *OrderItemModifierOptionUpdate) SetOptionPrice(v float64) *OrderItemModifierOptionUpdate {
	_u.mutation.ResetOptionPrice()
	_u.mutation.SetOptionPrice(v)
	return _u
}

// SetNillableOptionPrice sets the "option_price" field if the given value is not nil.
func (_u *OrderItemModifierOptionUpdate) SetNillableOptionPrice(v *float64) *OrderItemModifierOptionUpdate {
	if v != nil {
		_u.SetOptionPrice(*v)
	}
	return _u
}

// AddOptionPrice adds value to the "option_price" field.
func (_u *OrderItemModifierOptionUpdate) AddOptionPrice(v float64) *OrderItemModifierOptionUpdate {
	_u.mutation.AddOptionPrice(v)
	return _u
}

// SetOrderItem sets the "order_item" edge to the OrderItem entity.
func (_u *OrderItemModifierOptionUpdate) SetOrderItem(v *OrderItem) *OrderItemModifierOptionUpdate {
	return _u.SetOrderItemID(v.ID)
}

// SetModifierOption sets the "modifier_option" edge to the ModifierOption entity.
func (_u *OrderItemModifierOptionUpdate) SetModifierOption(v *ModifierOption) *OrderItemModifierOptionUpdate {
	return _u.SetModifierOptionID(v.ID)
}

// Mutation returns the OrderItemModifierOptionMutation object of the builder.
func (_u *OrderItemModifierOptionUpdate) Mutation() *OrderItemModifierOptionMutation {
	return _u.mutation
}

// ClearOrderItem clears the "order_item" edge to the OrderItem entity.
func (_u *OrderItemModifierOptionUpdate) ClearOrderItem() *OrderItemModifierOptionUpdate {
	_u.mutation.ClearOrderItem()
	return _u
}

// ClearModifierOption clears the "modifier_option" edge to the ModifierOption entity.
func (_u *OrderItemModifierOptionUpdate) ClearModifierOption() *OrderItemModifierOptionUpdate {
	_u.mutation.ClearModifierOption()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrderItemModifierOptionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderItemModifierOptionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrderItemModifierOptionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderItemModifierOptionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderItemModifierOptionUpdate) check() error {
	if v, ok := _u.mutation.Quantity(); ok {
		if err := orderitemmodifieroption.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "OrderItemModifierOption.quantity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OptionName(); ok {
		if err := orderitemmodifieroption.OptionNameValidator(v); err != nil {
			return &ValidationError{Name: "option_name", err: fmt.Errorf(`ent: validator failed for field "OrderItemModifierOption.option_name": %w`, err)}
		}
	}
	if _u.mutation.OrderItemCleared() && len(_u.mutation.OrderItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrderItemModifierOption.order_item"`)
	}
	if _u.mutation.ModifierOptionCleared() && len(_u.mutation.ModifierOptionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrderItemModifierOption.modifier_option"`)
	}
	return nil
}

func (_u *OrderItemModifierOptionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(orderitemmodifieroption.Table, orderitemmodifieroption.Columns, sqlgraph.NewFieldSpec(orderitemmodifieroption.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(orderitemmodifieroption.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(orderitemmodifieroption.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OptionName(); ok {
		_spec.SetField(orderitemmodifieroption.FieldOptionName, field.TypeString, value)
	}
	if value, ok := _u.mutation.OptionPrice(); ok {
		_spec.SetField(orderitemmodifieroption.FieldOptionPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOptionPrice(); ok {
		_spec.AddField(orderitemmodifieroption.FieldOptionPrice, field.TypeFloat64, value)
	}
	if _u.mutation.OrderItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderitemmodifieroption.OrderItemTable,
			Columns: []string{orderitemmodifieroption.OrderItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderitemmodifieroption.OrderItemTable,
			Columns: []string{orderitemmodifieroption.OrderItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ModifierOptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderitemmodifieroption.ModifierOptionTable,
			Columns: []string{orderitemmodifieroption.ModifierOptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modifieroption.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ModifierOptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderitemmodifieroption.ModifierOptionTable,
			Columns: []string{orderitemmodifieroption.ModifierOptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modifieroption.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orderitemmodifieroption.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrderItemModifierOptionUpdateOne is the builder for updating a single OrderItemModifierOption entity.
type OrderItemModifierOptionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrderItemModifierOptionMutation
}

// SetOrderItemID sets the "order_item_id" field.
func (_u *OrderItemModifierOptionUpdateOne) SetOrderItemID(v uuid.UUID) *OrderItemModifierOptionUpdateOne {
	_u.mutation.SetOrderItemID(v)
	return _u
}

// SetNillableOrderItemID sets the "order_item_id" field if the given value is not nil.
func (_u *OrderItemModifierOptionUpdateOne) SetNillableOrderItemID(v *uuid.UUID) *OrderItemModifierOptionUpdateOne {
	if v != nil {
		_u.SetOrderItemID(*v)
	}
	return _u
}

// SetModifierOptionID sets the "modifier_option_id" field.
func (_u *OrderItemModifierOptionUpdateOne) SetModifierOptionID(v uuid.UUID) *OrderItemModifierOptionUpdateOne {
	_u.mutation.SetModifierOptionID(v)
	return _u
}

// SetNillableModifierOptionID sets the "modifier_option_id" field if the given value is not nil.
func (_u *OrderItemModifierOptionUpdateOne) SetNillableModifierOptionID(v *uuid.UUID) *OrderItemModifierOptionUpdateOne {
	if v != nil {
		_u.SetModifierOptionID(*v)
	}
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *OrderItemModifierOptionUpdateOne) SetQuantity(v int) *OrderItemModifierOptionUpdateOne {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *OrderItemModifierOptionUpdateOne) SetNillableQuantity(v *int) *OrderItemModifierOptionUpdateOne {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *OrderItemModifierOptionUpdateOne) AddQuantity(v int) *OrderItemModifierOptionUpdateOne {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetOptionName sets the "option_name" field.
func (_u *OrderItemModifierOptionUpdateOne) SetOptionName(v string) *OrderItemModifierOptionUpdateOne {
	_u.mutation.SetOptionName(v)
	return _u
}

// SetNillableOptionName sets the "option_name" field if the given value is not nil.
func (_u *OrderItemModifierOptionUpdateOne) SetNillableOptionName(v *string) *OrderItemModifierOptionUpdateOne {
	if v != nil {
		_u.SetOptionName(*v)
	}
	return _u
}

// SetOptionPrice sets the "option_price" field.
func (_u *OrderItemModifierOptionUpdateOne) SetOptionPrice(v float64) *OrderItemModifierOptionUpdateOne {
	_u.mutation.ResetOptionPrice()
	_u.mutation.SetOptionPrice(v)
	return _u
}

// SetNillableOptionPrice sets the "option_price" field if the given value is not nil.
func (_u *OrderItemModifierOptionUpdateOne) SetNillableOptionPrice(v *float64) *OrderItemModifierOptionUpdateOne {
	if v != nil {
		_u.SetOptionPrice(*v)
	}
	return _u
}

// AddOptionPrice adds value to the "option_price" field.
func (_u *OrderItemModifierOptionUpdateOne) AddOptionPrice(v float64) *OrderItemModifierOptionUpdateOne {
	_u.mutation.AddOptionPrice(v)
	return _u
}

// SetOrderItem sets the "order_item" edge to the OrderItem entity.
func (_u *OrderItemModifierOptionUpdateOne) SetOrderItem(v *OrderItem) *OrderItemModifierOptionUpdateOne {
	return _u.SetOrderItemID(v.ID)
}

// SetModifierOption sets the "modifier_option" edge to the ModifierOption entity.
func (_u *OrderItemModifierOptionUpdateOne) SetModifierOption(v *ModifierOption) *OrderItemModifierOptionUpdateOne {
	return _u.SetModifierOptionID(v.ID)
}

// Mutation returns the OrderItemModifierOptionMutation object of the builder.
func (_u *OrderItemModifierOptionUpdateOne) Mutation() *OrderItemModifierOptionMutation {
	return _u.mutation
}

// ClearOrderItem clears the "order_item" edge to the OrderItem entity.
func (_u *OrderItemModifierOptionUpdateOne) ClearOrderItem() *OrderItemModifierOptionUpdateOne {
	_u.mutation.ClearOrderItem()
	return _u
}

// ClearModifierOption clears the "modifier_option" edge to the ModifierOption entity.
func (_u *OrderItemModifierOptionUpdateOne) ClearModifierOption() *OrderItemModifierOptionUpdateOne {
	_u.mutation.ClearModifierOption()
	return _u
}

// Where appends a list predicates to the OrderItemModifierOptionUpdate builder.
func (_u *OrderItemModifierOptionUpdateOne) Where(ps ...predicate.OrderItemModifierOption) *OrderItemModifierOptionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrderItemModifierOptionUpdateOne) Select(field string, fields ...string) *OrderItemModifierOptionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OrderItemModifierOption entity.
func (_u *OrderItemModifierOptionUpdateOne) Save(ctx context.Context) (*OrderItemModifierOption, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderItemModifierOptionUpdateOne) SaveX(ctx context.Context) *OrderItemModifierOption {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrderItemModifierOptionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderItemModifierOptionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderItemModifierOptionUpdateOne) check() error {
	if v, ok := _u.mutation.Quantity(); ok {
		if err := orderitemmodifieroption.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "OrderItemModifierOption.quantity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OptionName(); ok {
		if err := orderitemmodifieroption.OptionNameValidator(v); err != nil {
			return &ValidationError{Name: "option_name", err: fmt.Errorf(`ent: validator failed for field "OrderItemModifierOption.option_name": %w`, err)}
		}
	}
	if _u.mutation.OrderItemCleared() && len(_u.mutation.OrderItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrderItemModifierOption.order_item"`)
	}
	if _u.mutation.ModifierOptionCleared() && len(_u.mutation.ModifierOptionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrderItemModifierOption.modifier_option"`)
	}
	return nil
}

func (_u *OrderItemModifierOptionUpdateOne) sqlSave(ctx context.Context) (_node *OrderItemModifierOption, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(orderitemmodifieroption.Table, orderitemmodifieroption.Columns, sqlgraph.NewFieldSpec(orderitemmodifieroption.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OrderItemModifierOption.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, orderitemmodifieroption.FieldID)
		for _, f := range fields {
			if !orderitemmodifieroption.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != orderitemmodifieroption.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(orderitemmodifieroption.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(orderitemmodifieroption.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OptionName(); ok {
		_spec.SetField(orderitemmodifieroption.FieldOptionName, field.TypeString, value)
	}
	if value, ok := _u.mutation.OptionPrice(); ok {
		_spec.SetField(orderitemmodifieroption.FieldOptionPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOptionPrice(); ok {
		_spec.AddField(orderitemmodifieroption.FieldOptionPrice, field.TypeFloat64, value)
	}
	if _u.mutation.OrderItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderitemmodifieroption.OrderItemTable,
			Columns: []string{orderitemmodifieroption.OrderItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderitemmodifieroption.OrderItemTable,
			Columns: []string{orderitemmodifieroption.OrderItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ModifierOptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderitemmodifieroption.ModifierOptionTable,
			Columns: []string{orderitemmodifieroption.ModifierOptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modifieroption.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ModifierOptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderitemmodifieroption.ModifierOptionTable,
			Columns: []string{orderitemmodifieroption.ModifierOptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modifieroption.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OrderItemModifierOption{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orderitemmodifieroption.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
