// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Jiruu246/rms/internal/ent/refreshtoken"
	"github.com/Jiruu246/rms/internal/ent/user"
	"github.com/google/uuid"
)

// RefreshTokenCreate is the builder for creating a RefreshToken entity.
type RefreshTokenCreate struct {
	config
	mutation *RefreshTokenMutation
	hooks    []Hook
}

// SetUpdateTime sets the "update_time" field.
func (_c *RefreshTokenCreate) SetUpdateTime(v time.Time) *RefreshTokenCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *RefreshTokenCreate) SetNillableUpdateTime(v *time.Time) *RefreshTokenCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *RefreshTokenCreate) SetUserID(v uuid.UUID) *RefreshTokenCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetToken sets the "token" field.
func (_c *RefreshTokenCreate) SetToken(v string) *RefreshTokenCreate {
	_c.mutation.SetToken(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *RefreshTokenCreate) SetExpiresAt(v time.Time) *RefreshTokenCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetRevoked sets the "revoked" field.
func (_c *RefreshTokenCreate) SetRevoked(v bool) *RefreshTokenCreate {
	_c.mutation.SetRevoked(v)
	return _c
}

// SetNillableRevoked sets the "revoked" field if the given value is not nil.
func (_c *RefreshTokenCreate) SetNillableRevoked(v *bool) *RefreshTokenCreate {
	if v != nil {
		_c.SetRevoked(*v)
	}
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *RefreshTokenCreate) SetRevokedAt(v time.Time) *RefreshTokenCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *RefreshTokenCreate) SetNillableRevokedAt(v *time.Time) *RefreshTokenCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// SetReplacedBy sets the "replaced_by" field.
func (_c *RefreshTokenCreate) SetReplacedBy(v uuid.UUID) *RefreshTokenCreate {
	_c.mutation.SetReplacedBy(v)
	return _c
}

// SetNillableReplacedBy sets the "replaced_by" field if the given value is not nil.
func (_c *RefreshTokenCreate) SetNillableReplacedBy(v *uuid.UUID) *RefreshTokenCreate {
	if v != nil {
		_c.SetReplacedBy(*v)
	}
	return _c
}

// SetLastUsedAt sets the "last_used_at" field.
func (_c *RefreshTokenCreate) SetLastUsedAt(v time.Time) *RefreshTokenCreate {
	_c.mutation.SetLastUsedAt(v)
	return _c
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_c *RefreshTokenCreate) SetNillableLastUsedAt(v *time.Time) *RefreshTokenCreate {
	if v != nil {
		_c.SetLastUsedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RefreshTokenCreate) SetID(v uuid.UUID) *RefreshTokenCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RefreshTokenCreate) SetNillableID(v *uuid.UUID) *RefreshTokenCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *RefreshTokenCreate) SetUser(v *User) *RefreshTokenCreate {
	return _c.SetUserID(v.ID)
}

// SetReplacedByTokenID sets the "replaced_by_token" edge to the RefreshToken entity by ID.
func (_c *RefreshTokenCreate) SetReplacedByTokenID(id uuid.UUID) *RefreshTokenCreate {
	_c.mutation.SetReplacedByTokenID(id)
	return _c
}

// SetNillableReplacedByTokenID sets the "replaced_by_token" edge to the RefreshToken entity by ID if the given value is not nil.
func (_c *RefreshTokenCreate) SetNillableReplacedByTokenID(id *uuid.UUID) *RefreshTokenCreate {
	if id != nil {
		_c = _c.SetReplacedByTokenID(*id)
	}
	return _c
}

// SetReplacedByToken sets the "replaced_by_token" edge to the RefreshToken entity.
func (_c *RefreshTokenCreate) SetReplacedByToken(v *RefreshToken) *RefreshTokenCreate {
	return _c.SetReplacedByTokenID(v.ID)
}

// Mutation returns the RefreshTokenMutation object of the builder.
func (_c *RefreshTokenCreate) Mutation() *RefreshTokenMutation {
	return _c.mutation
}

// Save creates the RefreshToken in the database.
func (_c *RefreshTokenCreate) Save(ctx context.Context) (*RefreshToken, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RefreshTokenCreate) SaveX(ctx context.Context) *RefreshToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RefreshTokenCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RefreshTokenCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RefreshTokenCreate) defaults() {
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := refreshtoken.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.Revoked(); !ok {
		v := refreshtoken.DefaultRevoked
		_c.mutation.SetRevoked(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := refreshtoken.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RefreshTokenCreate) check() error {
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "RefreshToken.update_time"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "RefreshToken.user_id"`)}
	}
	if _, ok := _c.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "RefreshToken.token"`)}
	}
	if v, ok := _c.mutation.Token(); ok {
		if err := refreshtoken.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "RefreshToken.token": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "RefreshToken.expires_at"`)}
	}
	if _, ok := _c.mutation.Revoked(); !ok {
		return &ValidationError{Name: "revoked", err: errors.New(`ent: missing required field "RefreshToken.revoked"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "RefreshToken.user"`)}
	}
	return nil
}

func (_c *RefreshTokenCreate) sqlSave(ctx context.Context) (*RefreshToken, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RefreshTokenCreate) createSpec() (*RefreshToken, *sqlgraph.CreateSpec) {
	var (
		_node = &RefreshToken{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(refreshtoken.Table, sqlgraph.NewFieldSpec(refreshtoken.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(refreshtoken.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.Token(); ok {
		_spec.SetField(refreshtoken.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(refreshtoken.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.Revoked(); ok {
		_spec.SetField(refreshtoken.FieldRevoked, field.TypeBool, value)
		_node.Revoked = value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(refreshtoken.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	if value, ok := _c.mutation.LastUsedAt(); ok {
		_spec.SetField(refreshtoken.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   refreshtoken.UserTable,
			Columns: []string{refreshtoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ReplacedByTokenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   refreshtoken.ReplacedByTokenTable,
			Columns: []string{refreshtoken.ReplacedByTokenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(refreshtoken.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ReplacedBy = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RefreshTokenCreateBulk is the builder for creating many RefreshToken entities in bulk.
type RefreshTokenCreateBulk struct {
	config
	err      error
	builders []*RefreshTokenCreate
}

// Save creates the RefreshToken entities in the database.
func (_c *RefreshTokenCreateBulk) Save(ctx context.Context) ([]*RefreshToken, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RefreshToken, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RefreshTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RefreshTokenCreateBulk) SaveX(ctx context.Context) []*RefreshToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RefreshTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RefreshTokenCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
