// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Jiruu246/rms/internal/ent/category"
	"github.com/Jiruu246/rms/internal/ent/menuitem"
	"github.com/Jiruu246/rms/internal/ent/restaurant"
	"github.com/Jiruu246/rms/internal/ent/user"
	"github.com/google/uuid"
)

// RestaurantCreate is the builder for creating a Restaurant entity.
type RestaurantCreate struct {
	config
	mutation *RestaurantMutation
	hooks    []Hook
}

// SetUpdateTime sets the "update_time" field.
func (_c *RestaurantCreate) SetUpdateTime(v time.Time) *RestaurantCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *RestaurantCreate) SetNillableUpdateTime(v *time.Time) *RestaurantCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *RestaurantCreate) SetName(v string) *RestaurantCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *RestaurantCreate) SetDescription(v string) *RestaurantCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *RestaurantCreate) SetNillableDescription(v *string) *RestaurantCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetPhone sets the "phone" field.
func (_c *RestaurantCreate) SetPhone(v string) *RestaurantCreate {
	_c.mutation.SetPhone(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *RestaurantCreate) SetEmail(v string) *RestaurantCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetAddress sets the "address" field.
func (_c *RestaurantCreate) SetAddress(v string) *RestaurantCreate {
	_c.mutation.SetAddress(v)
	return _c
}

// SetCity sets the "city" field.
func (_c *RestaurantCreate) SetCity(v string) *RestaurantCreate {
	_c.mutation.SetCity(v)
	return _c
}

// SetState sets the "state" field.
func (_c *RestaurantCreate) SetState(v string) *RestaurantCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetZipCode sets the "zip_code" field.
func (_c *RestaurantCreate) SetZipCode(v string) *RestaurantCreate {
	_c.mutation.SetZipCode(v)
	return _c
}

// SetCountry sets the "country" field.
func (_c *RestaurantCreate) SetCountry(v string) *RestaurantCreate {
	_c.mutation.SetCountry(v)
	return _c
}

// SetLogoURL sets the "logo_url" field.
func (_c *RestaurantCreate) SetLogoURL(v string) *RestaurantCreate {
	_c.mutation.SetLogoURL(v)
	return _c
}

// SetNillableLogoURL sets the "logo_url" field if the given value is not nil.
func (_c *RestaurantCreate) SetNillableLogoURL(v *string) *RestaurantCreate {
	if v != nil {
		_c.SetLogoURL(*v)
	}
	return _c
}

// SetCoverImageURL sets the "cover_image_url" field.
func (_c *RestaurantCreate) SetCoverImageURL(v string) *RestaurantCreate {
	_c.mutation.SetCoverImageURL(v)
	return _c
}

// SetNillableCoverImageURL sets the "cover_image_url" field if the given value is not nil.
func (_c *RestaurantCreate) SetNillableCoverImageURL(v *string) *RestaurantCreate {
	if v != nil {
		_c.SetCoverImageURL(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *RestaurantCreate) SetStatus(v restaurant.Status) *RestaurantCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *RestaurantCreate) SetNillableStatus(v *restaurant.Status) *RestaurantCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetOperatingHours sets the "operating_hours" field.
func (_c *RestaurantCreate) SetOperatingHours(v map[string]interface{}) *RestaurantCreate {
	_c.mutation.SetOperatingHours(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *RestaurantCreate) SetCurrency(v string) *RestaurantCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *RestaurantCreate) SetUserID(v uuid.UUID) *RestaurantCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *RestaurantCreate) SetID(v uuid.UUID) *RestaurantCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RestaurantCreate) SetNillableID(v *uuid.UUID) *RestaurantCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *RestaurantCreate) SetUser(v *User) *RestaurantCreate {
	return _c.SetUserID(v.ID)
}

// AddMenuItemIDs adds the "menu_items" edge to the MenuItem entity by IDs.
func (_c *RestaurantCreate) AddMenuItemIDs(ids ...int64) *RestaurantCreate {
	_c.mutation.AddMenuItemIDs(ids...)
	return _c
}

// AddMenuItems adds the "menu_items" edges to the MenuItem entity.
func (_c *RestaurantCreate) AddMenuItems(v ...*MenuItem) *RestaurantCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMenuItemIDs(ids...)
}

// AddCategoryIDs adds the "categories" edge to the Category entity by IDs.
func (_c *RestaurantCreate) AddCategoryIDs(ids ...uuid.UUID) *RestaurantCreate {
	_c.mutation.AddCategoryIDs(ids...)
	return _c
}

// AddCategories adds the "categories" edges to the Category entity.
func (_c *RestaurantCreate) AddCategories(v ...*Category) *RestaurantCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCategoryIDs(ids...)
}

// Mutation returns the RestaurantMutation object of the builder.
func (_c *RestaurantCreate) Mutation() *RestaurantMutation {
	return _c.mutation
}

// Save creates the Restaurant in the database.
func (_c *RestaurantCreate) Save(ctx context.Context) (*Restaurant, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RestaurantCreate) SaveX(ctx context.Context) *Restaurant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RestaurantCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RestaurantCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RestaurantCreate) defaults() {
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := restaurant.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := restaurant.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := restaurant.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RestaurantCreate) check() error {
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Restaurant.update_time"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Restaurant.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := restaurant.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Restaurant.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Phone(); !ok {
		return &ValidationError{Name: "phone", err: errors.New(`ent: missing required field "Restaurant.phone"`)}
	}
	if v, ok := _c.mutation.Phone(); ok {
		if err := restaurant.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "Restaurant.phone": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "Restaurant.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := restaurant.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Restaurant.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`ent: missing required field "Restaurant.address"`)}
	}
	if v, ok := _c.mutation.Address(); ok {
		if err := restaurant.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "Restaurant.address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.City(); !ok {
		return &ValidationError{Name: "city", err: errors.New(`ent: missing required field "Restaurant.city"`)}
	}
	if v, ok := _c.mutation.City(); ok {
		if err := restaurant.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "Restaurant.city": %w`, err)}
		}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "Restaurant.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := restaurant.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Restaurant.state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ZipCode(); !ok {
		return &ValidationError{Name: "zip_code", err: errors.New(`ent: missing required field "Restaurant.zip_code"`)}
	}
	if v, ok := _c.mutation.ZipCode(); ok {
		if err := restaurant.ZipCodeValidator(v); err != nil {
			return &ValidationError{Name: "zip_code", err: fmt.Errorf(`ent: validator failed for field "Restaurant.zip_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Country(); !ok {
		return &ValidationError{Name: "country", err: errors.New(`ent: missing required field "Restaurant.country"`)}
	}
	if v, ok := _c.mutation.Country(); ok {
		if err := restaurant.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "Restaurant.country": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Restaurant.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := restaurant.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Restaurant.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "Restaurant.currency"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Restaurant.user_id"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Restaurant.user"`)}
	}
	return nil
}

func (_c *RestaurantCreate) sqlSave(ctx context.Context) (*Restaurant, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RestaurantCreate) createSpec() (*Restaurant, *sqlgraph.CreateSpec) {
	var (
		_node = &Restaurant{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(restaurant.Table, sqlgraph.NewFieldSpec(restaurant.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(restaurant.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(restaurant.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(restaurant.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Phone(); ok {
		_spec.SetField(restaurant.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(restaurant.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Address(); ok {
		_spec.SetField(restaurant.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := _c.mutation.City(); ok {
		_spec.SetField(restaurant.FieldCity, field.TypeString, value)
		_node.City = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(restaurant.FieldState, field.TypeString, value)
		_node.State = value
	}
	if value, ok := _c.mutation.ZipCode(); ok {
		_spec.SetField(restaurant.FieldZipCode, field.TypeString, value)
		_node.ZipCode = value
	}
	if value, ok := _c.mutation.Country(); ok {
		_spec.SetField(restaurant.FieldCountry, field.TypeString, value)
		_node.Country = value
	}
	if value, ok := _c.mutation.LogoURL(); ok {
		_spec.SetField(restaurant.FieldLogoURL, field.TypeString, value)
		_node.LogoURL = value
	}
	if value, ok := _c.mutation.CoverImageURL(); ok {
		_spec.SetField(restaurant.FieldCoverImageURL, field.TypeString, value)
		_node.CoverImageURL = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(restaurant.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.OperatingHours(); ok {
		_spec.SetField(restaurant.FieldOperatingHours, field.TypeJSON, value)
		_node.OperatingHours = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(restaurant.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   restaurant.UserTable,
			Columns: []string{restaurant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MenuItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   restaurant.MenuItemsTable,
			Columns: []string{restaurant.MenuItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menuitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CategoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   restaurant.CategoriesTable,
			Columns: []string{restaurant.CategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RestaurantCreateBulk is the builder for creating many Restaurant entities in bulk.
type RestaurantCreateBulk struct {
	config
	err      error
	builders []*RestaurantCreate
}

// Save creates the Restaurant entities in the database.
func (_c *RestaurantCreateBulk) Save(ctx context.Context) ([]*Restaurant, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Restaurant, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RestaurantMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RestaurantCreateBulk) SaveX(ctx context.Context) []*Restaurant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RestaurantCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RestaurantCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
