// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Jiruu246/rms/internal/ent/restaurant"
	"github.com/Jiruu246/rms/internal/ent/user"
	"github.com/google/uuid"
)

// Restaurant is the model entity for the Restaurant schema.
type Restaurant struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Phone holds the value of the "phone" field.
	Phone string `json:"phone,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// Address holds the value of the "address" field.
	Address string `json:"address,omitempty"`
	// City holds the value of the "city" field.
	City string `json:"city,omitempty"`
	// State holds the value of the "state" field.
	State string `json:"state,omitempty"`
	// ZipCode holds the value of the "zip_code" field.
	ZipCode string `json:"zip_code,omitempty"`
	// Country holds the value of the "country" field.
	Country string `json:"country,omitempty"`
	// LogoURL holds the value of the "logo_url" field.
	LogoURL string `json:"logo_url,omitempty"`
	// CoverImageURL holds the value of the "cover_image_url" field.
	CoverImageURL string `json:"cover_image_url,omitempty"`
	// Status holds the value of the "status" field.
	Status restaurant.Status `json:"status,omitempty"`
	// OperatingHours holds the value of the "operating_hours" field.
	OperatingHours map[string]interface{} `json:"operating_hours,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RestaurantQuery when eager-loading is set.
	Edges        RestaurantEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RestaurantEdges holds the relations/edges for other nodes in the graph.
type RestaurantEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// MenuItems holds the value of the menu_items edge.
	MenuItems []*MenuItem `json:"menu_items,omitempty"`
	// Categories holds the value of the categories edge.
	Categories []*Category `json:"categories,omitempty"`
	// Modifiers holds the value of the modifiers edge.
	Modifiers []*Modifier `json:"modifiers,omitempty"`
	// Orders holds the value of the orders edge.
	Orders []*Order `json:"orders,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RestaurantEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// MenuItemsOrErr returns the MenuItems value or an error if the edge
// was not loaded in eager-loading.
func (e RestaurantEdges) MenuItemsOrErr() ([]*MenuItem, error) {
	if e.loadedTypes[1] {
		return e.MenuItems, nil
	}
	return nil, &NotLoadedError{edge: "menu_items"}
}

// CategoriesOrErr returns the Categories value or an error if the edge
// was not loaded in eager-loading.
func (e RestaurantEdges) CategoriesOrErr() ([]*Category, error) {
	if e.loadedTypes[2] {
		return e.Categories, nil
	}
	return nil, &NotLoadedError{edge: "categories"}
}

// ModifiersOrErr returns the Modifiers value or an error if the edge
// was not loaded in eager-loading.
func (e RestaurantEdges) ModifiersOrErr() ([]*Modifier, error) {
	if e.loadedTypes[3] {
		return e.Modifiers, nil
	}
	return nil, &NotLoadedError{edge: "modifiers"}
}

// OrdersOrErr returns the Orders value or an error if the edge
// was not loaded in eager-loading.
func (e RestaurantEdges) OrdersOrErr() ([]*Order, error) {
	if e.loadedTypes[4] {
		return e.Orders, nil
	}
	return nil, &NotLoadedError{edge: "orders"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Restaurant) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case restaurant.FieldOperatingHours:
			values[i] = new([]byte)
		case restaurant.FieldName, restaurant.FieldDescription, restaurant.FieldPhone, restaurant.FieldEmail, restaurant.FieldAddress, restaurant.FieldCity, restaurant.FieldState, restaurant.FieldZipCode, restaurant.FieldCountry, restaurant.FieldLogoURL, restaurant.FieldCoverImageURL, restaurant.FieldStatus, restaurant.FieldCurrency:
			values[i] = new(sql.NullString)
		case restaurant.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		case restaurant.FieldID, restaurant.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Restaurant fields.
func (_m *Restaurant) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case restaurant.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case restaurant.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case restaurant.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case restaurant.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case restaurant.FieldPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phone", values[i])
			} else if value.Valid {
				_m.Phone = value.String
			}
		case restaurant.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case restaurant.FieldAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address", values[i])
			} else if value.Valid {
				_m.Address = value.String
			}
		case restaurant.FieldCity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field city", values[i])
			} else if value.Valid {
				_m.City = value.String
			}
		case restaurant.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = value.String
			}
		case restaurant.FieldZipCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field zip_code", values[i])
			} else if value.Valid {
				_m.ZipCode = value.String
			}
		case restaurant.FieldCountry:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field country", values[i])
			} else if value.Valid {
				_m.Country = value.String
			}
		case restaurant.FieldLogoURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field logo_url", values[i])
			} else if value.Valid {
				_m.LogoURL = value.String
			}
		case restaurant.FieldCoverImageURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cover_image_url", values[i])
			} else if value.Valid {
				_m.CoverImageURL = value.String
			}
		case restaurant.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = restaurant.Status(value.String)
			}
		case restaurant.FieldOperatingHours:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field operating_hours", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.OperatingHours); err != nil {
					return fmt.Errorf("unmarshal field operating_hours: %w", err)
				}
			}
		case restaurant.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case restaurant.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Restaurant.
// This includes values selected through modifiers, order, etc.
func (_m *Restaurant) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Restaurant entity.
func (_m *Restaurant) QueryUser() *UserQuery {
	return NewRestaurantClient(_m.config).QueryUser(_m)
}

// QueryMenuItems queries the "menu_items" edge of the Restaurant entity.
func (_m *Restaurant) QueryMenuItems() *MenuItemQuery {
	return NewRestaurantClient(_m.config).QueryMenuItems(_m)
}

// QueryCategories queries the "categories" edge of the Restaurant entity.
func (_m *Restaurant) QueryCategories() *CategoryQuery {
	return NewRestaurantClient(_m.config).QueryCategories(_m)
}

// QueryModifiers queries the "modifiers" edge of the Restaurant entity.
func (_m *Restaurant) QueryModifiers() *ModifierQuery {
	return NewRestaurantClient(_m.config).QueryModifiers(_m)
}

// QueryOrders queries the "orders" edge of the Restaurant entity.
func (_m *Restaurant) QueryOrders() *OrderQuery {
	return NewRestaurantClient(_m.config).QueryOrders(_m)
}

// Update returns a builder for updating this Restaurant.
// Note that you need to call Restaurant.Unwrap() before calling this method if this Restaurant
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Restaurant) Update() *RestaurantUpdateOne {
	return NewRestaurantClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Restaurant entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Restaurant) Unwrap() *Restaurant {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Restaurant is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Restaurant) String() string {
	var builder strings.Builder
	builder.WriteString("Restaurant(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("phone=")
	builder.WriteString(_m.Phone)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("address=")
	builder.WriteString(_m.Address)
	builder.WriteString(", ")
	builder.WriteString("city=")
	builder.WriteString(_m.City)
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(_m.State)
	builder.WriteString(", ")
	builder.WriteString("zip_code=")
	builder.WriteString(_m.ZipCode)
	builder.WriteString(", ")
	builder.WriteString("country=")
	builder.WriteString(_m.Country)
	builder.WriteString(", ")
	builder.WriteString("logo_url=")
	builder.WriteString(_m.LogoURL)
	builder.WriteString(", ")
	builder.WriteString("cover_image_url=")
	builder.WriteString(_m.CoverImageURL)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("operating_hours=")
	builder.WriteString(fmt.Sprintf("%v", _m.OperatingHours))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteByte(')')
	return builder.String()
}

// Restaurants is a parsable slice of Restaurant.
type Restaurants []*Restaurant
