// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Jiruu246/rms/internal/ent/category"
	"github.com/Jiruu246/rms/internal/ent/menuitem"
	"github.com/Jiruu246/rms/internal/ent/modifier"
	"github.com/Jiruu246/rms/internal/ent/predicate"
	"github.com/Jiruu246/rms/internal/ent/restaurant"
	"github.com/Jiruu246/rms/internal/ent/user"
	"github.com/google/uuid"
)

// RestaurantQuery is the builder for querying Restaurant entities.
type RestaurantQuery struct {
	config
	ctx            *QueryContext
	order          []restaurant.OrderOption
	inters         []Interceptor
	predicates     []predicate.Restaurant
	withUser       *UserQuery
	withMenuItems  *MenuItemQuery
	withCategories *CategoryQuery
	withModifiers  *ModifierQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RestaurantQuery builder.
func (_q *RestaurantQuery) Where(ps ...predicate.Restaurant) *RestaurantQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *RestaurantQuery) Limit(limit int) *RestaurantQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *RestaurantQuery) Offset(offset int) *RestaurantQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *RestaurantQuery) Unique(unique bool) *RestaurantQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *RestaurantQuery) Order(o ...restaurant.OrderOption) *RestaurantQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUser chains the current query on the "user" edge.
func (_q *RestaurantQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(restaurant.Table, restaurant.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, restaurant.UserTable, restaurant.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMenuItems chains the current query on the "menu_items" edge.
func (_q *RestaurantQuery) QueryMenuItems() *MenuItemQuery {
	query := (&MenuItemClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(restaurant.Table, restaurant.FieldID, selector),
			sqlgraph.To(menuitem.Table, menuitem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, restaurant.MenuItemsTable, restaurant.MenuItemsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCategories chains the current query on the "categories" edge.
func (_q *RestaurantQuery) QueryCategories() *CategoryQuery {
	query := (&CategoryClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(restaurant.Table, restaurant.FieldID, selector),
			sqlgraph.To(category.Table, category.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, restaurant.CategoriesTable, restaurant.CategoriesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryModifiers chains the current query on the "modifiers" edge.
func (_q *RestaurantQuery) QueryModifiers() *ModifierQuery {
	query := (&ModifierClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(restaurant.Table, restaurant.FieldID, selector),
			sqlgraph.To(modifier.Table, modifier.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, restaurant.ModifiersTable, restaurant.ModifiersColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Restaurant entity from the query.
// Returns a *NotFoundError when no Restaurant was found.
func (_q *RestaurantQuery) First(ctx context.Context) (*Restaurant, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{restaurant.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *RestaurantQuery) FirstX(ctx context.Context) *Restaurant {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Restaurant ID from the query.
// Returns a *NotFoundError when no Restaurant ID was found.
func (_q *RestaurantQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{restaurant.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *RestaurantQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Restaurant entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Restaurant entity is found.
// Returns a *NotFoundError when no Restaurant entities are found.
func (_q *RestaurantQuery) Only(ctx context.Context) (*Restaurant, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{restaurant.Label}
	default:
		return nil, &NotSingularError{restaurant.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *RestaurantQuery) OnlyX(ctx context.Context) *Restaurant {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Restaurant ID in the query.
// Returns a *NotSingularError when more than one Restaurant ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *RestaurantQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{restaurant.Label}
	default:
		err = &NotSingularError{restaurant.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *RestaurantQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Restaurants.
func (_q *RestaurantQuery) All(ctx context.Context) ([]*Restaurant, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Restaurant, *RestaurantQuery]()
	return withInterceptors[[]*Restaurant](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *RestaurantQuery) AllX(ctx context.Context) []*Restaurant {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Restaurant IDs.
func (_q *RestaurantQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(restaurant.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *RestaurantQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *RestaurantQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*RestaurantQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *RestaurantQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *RestaurantQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *RestaurantQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RestaurantQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *RestaurantQuery) Clone() *RestaurantQuery {
	if _q == nil {
		return nil
	}
	return &RestaurantQuery{
		config:         _q.config,
		ctx:            _q.ctx.Clone(),
		order:          append([]restaurant.OrderOption{}, _q.order...),
		inters:         append([]Interceptor{}, _q.inters...),
		predicates:     append([]predicate.Restaurant{}, _q.predicates...),
		withUser:       _q.withUser.Clone(),
		withMenuItems:  _q.withMenuItems.Clone(),
		withCategories: _q.withCategories.Clone(),
		withModifiers:  _q.withModifiers.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RestaurantQuery) WithUser(opts ...func(*UserQuery)) *RestaurantQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithMenuItems tells the query-builder to eager-load the nodes that are connected to
// the "menu_items" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RestaurantQuery) WithMenuItems(opts ...func(*MenuItemQuery)) *RestaurantQuery {
	query := (&MenuItemClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMenuItems = query
	return _q
}

// WithCategories tells the query-builder to eager-load the nodes that are connected to
// the "categories" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RestaurantQuery) WithCategories(opts ...func(*CategoryQuery)) *RestaurantQuery {
	query := (&CategoryClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCategories = query
	return _q
}

// WithModifiers tells the query-builder to eager-load the nodes that are connected to
// the "modifiers" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RestaurantQuery) WithModifiers(opts ...func(*ModifierQuery)) *RestaurantQuery {
	query := (&ModifierClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withModifiers = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UpdateTime time.Time `json:"update_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Restaurant.Query().
//		GroupBy(restaurant.FieldUpdateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *RestaurantQuery) GroupBy(field string, fields ...string) *RestaurantGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RestaurantGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = restaurant.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UpdateTime time.Time `json:"update_time,omitempty"`
//	}
//
//	client.Restaurant.Query().
//		Select(restaurant.FieldUpdateTime).
//		Scan(ctx, &v)
func (_q *RestaurantQuery) Select(fields ...string) *RestaurantSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &RestaurantSelect{RestaurantQuery: _q}
	sbuild.label = restaurant.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RestaurantSelect configured with the given aggregations.
func (_q *RestaurantQuery) Aggregate(fns ...AggregateFunc) *RestaurantSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *RestaurantQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !restaurant.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *RestaurantQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Restaurant, error) {
	var (
		nodes       = []*Restaurant{}
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withUser != nil,
			_q.withMenuItems != nil,
			_q.withCategories != nil,
			_q.withModifiers != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Restaurant).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Restaurant{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *Restaurant, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withMenuItems; query != nil {
		if err := _q.loadMenuItems(ctx, query, nodes,
			func(n *Restaurant) { n.Edges.MenuItems = []*MenuItem{} },
			func(n *Restaurant, e *MenuItem) { n.Edges.MenuItems = append(n.Edges.MenuItems, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCategories; query != nil {
		if err := _q.loadCategories(ctx, query, nodes,
			func(n *Restaurant) { n.Edges.Categories = []*Category{} },
			func(n *Restaurant, e *Category) { n.Edges.Categories = append(n.Edges.Categories, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withModifiers; query != nil {
		if err := _q.loadModifiers(ctx, query, nodes,
			func(n *Restaurant) { n.Edges.Modifiers = []*Modifier{} },
			func(n *Restaurant, e *Modifier) { n.Edges.Modifiers = append(n.Edges.Modifiers, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *RestaurantQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*Restaurant, init func(*Restaurant), assign func(*Restaurant, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Restaurant)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *RestaurantQuery) loadMenuItems(ctx context.Context, query *MenuItemQuery, nodes []*Restaurant, init func(*Restaurant), assign func(*Restaurant, *MenuItem)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Restaurant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(menuitem.FieldRestaurantID)
	}
	query.Where(predicate.MenuItem(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(restaurant.MenuItemsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.RestaurantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "restaurant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *RestaurantQuery) loadCategories(ctx context.Context, query *CategoryQuery, nodes []*Restaurant, init func(*Restaurant), assign func(*Restaurant, *Category)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Restaurant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(category.FieldRestaurantID)
	}
	query.Where(predicate.Category(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(restaurant.CategoriesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.RestaurantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "restaurant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *RestaurantQuery) loadModifiers(ctx context.Context, query *ModifierQuery, nodes []*Restaurant, init func(*Restaurant), assign func(*Restaurant, *Modifier)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Restaurant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(modifier.FieldRestaurantID)
	}
	query.Where(predicate.Modifier(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(restaurant.ModifiersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.RestaurantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "restaurant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *RestaurantQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *RestaurantQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(restaurant.Table, restaurant.Columns, sqlgraph.NewFieldSpec(restaurant.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, restaurant.FieldID)
		for i := range fields {
			if fields[i] != restaurant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(restaurant.FieldUserID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *RestaurantQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(restaurant.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = restaurant.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RestaurantGroupBy is the group-by builder for Restaurant entities.
type RestaurantGroupBy struct {
	selector
	build *RestaurantQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *RestaurantGroupBy) Aggregate(fns ...AggregateFunc) *RestaurantGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *RestaurantGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RestaurantQuery, *RestaurantGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *RestaurantGroupBy) sqlScan(ctx context.Context, root *RestaurantQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RestaurantSelect is the builder for selecting fields of Restaurant entities.
type RestaurantSelect struct {
	*RestaurantQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *RestaurantSelect) Aggregate(fns ...AggregateFunc) *RestaurantSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *RestaurantSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RestaurantQuery, *RestaurantSelect](ctx, _s.RestaurantQuery, _s, _s.inters, v)
}

func (_s *RestaurantSelect) sqlScan(ctx context.Context, root *RestaurantQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
