// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Jiruu246/rms/internal/ent/category"
	"github.com/Jiruu246/rms/internal/ent/menuitem"
	"github.com/Jiruu246/rms/internal/ent/modifier"
	"github.com/Jiruu246/rms/internal/ent/modifieroption"
	"github.com/Jiruu246/rms/internal/ent/restaurant"
	"github.com/Jiruu246/rms/internal/ent/schema"
	"github.com/Jiruu246/rms/internal/ent/user"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	categoryMixin := schema.Category{}.Mixin()
	categoryMixinFields0 := categoryMixin[0].Fields()
	_ = categoryMixinFields0
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescUpdateTime is the schema descriptor for update_time field.
	categoryDescUpdateTime := categoryMixinFields0[0].Descriptor()
	// category.DefaultUpdateTime holds the default value on creation for the update_time field.
	category.DefaultUpdateTime = categoryDescUpdateTime.Default.(func() time.Time)
	// category.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	category.UpdateDefaultUpdateTime = categoryDescUpdateTime.UpdateDefault.(func() time.Time)
	// categoryDescName is the schema descriptor for name field.
	categoryDescName := categoryFields[1].Descriptor()
	// category.NameValidator is a validator for the "name" field. It is called by the builders before save.
	category.NameValidator = func() func(string) error {
		validators := categoryDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// categoryDescDescription is the schema descriptor for description field.
	categoryDescDescription := categoryFields[2].Descriptor()
	// category.DefaultDescription holds the default value on creation for the description field.
	category.DefaultDescription = categoryDescDescription.Default.(string)
	// category.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	category.DescriptionValidator = categoryDescDescription.Validators[0].(func(string) error)
	// categoryDescDisplayOrder is the schema descriptor for display_order field.
	categoryDescDisplayOrder := categoryFields[3].Descriptor()
	// category.DefaultDisplayOrder holds the default value on creation for the display_order field.
	category.DefaultDisplayOrder = categoryDescDisplayOrder.Default.(int)
	// category.DisplayOrderValidator is a validator for the "display_order" field. It is called by the builders before save.
	category.DisplayOrderValidator = categoryDescDisplayOrder.Validators[0].(func(int) error)
	// categoryDescIsActive is the schema descriptor for is_active field.
	categoryDescIsActive := categoryFields[4].Descriptor()
	// category.DefaultIsActive holds the default value on creation for the is_active field.
	category.DefaultIsActive = categoryDescIsActive.Default.(bool)
	// categoryDescID is the schema descriptor for id field.
	categoryDescID := categoryFields[0].Descriptor()
	// category.DefaultID holds the default value on creation for the id field.
	category.DefaultID = categoryDescID.Default.(func() uuid.UUID)
	menuitemMixin := schema.MenuItem{}.Mixin()
	menuitemMixinFields0 := menuitemMixin[0].Fields()
	_ = menuitemMixinFields0
	menuitemFields := schema.MenuItem{}.Fields()
	_ = menuitemFields
	// menuitemDescUpdateTime is the schema descriptor for update_time field.
	menuitemDescUpdateTime := menuitemMixinFields0[0].Descriptor()
	// menuitem.DefaultUpdateTime holds the default value on creation for the update_time field.
	menuitem.DefaultUpdateTime = menuitemDescUpdateTime.Default.(func() time.Time)
	// menuitem.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	menuitem.UpdateDefaultUpdateTime = menuitemDescUpdateTime.UpdateDefault.(func() time.Time)
	// menuitemDescName is the schema descriptor for name field.
	menuitemDescName := menuitemFields[1].Descriptor()
	// menuitem.NameValidator is a validator for the "name" field. It is called by the builders before save.
	menuitem.NameValidator = func() func(string) error {
		validators := menuitemDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// menuitemDescDescription is the schema descriptor for description field.
	menuitemDescDescription := menuitemFields[2].Descriptor()
	// menuitem.DefaultDescription holds the default value on creation for the description field.
	menuitem.DefaultDescription = menuitemDescDescription.Default.(string)
	// menuitem.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	menuitem.DescriptionValidator = menuitemDescDescription.Validators[0].(func(string) error)
	// menuitemDescPrice is the schema descriptor for price field.
	menuitemDescPrice := menuitemFields[3].Descriptor()
	// menuitem.PriceValidator is a validator for the "price" field. It is called by the builders before save.
	menuitem.PriceValidator = menuitemDescPrice.Validators[0].(func(float64) error)
	// menuitemDescIsAvailable is the schema descriptor for is_available field.
	menuitemDescIsAvailable := menuitemFields[5].Descriptor()
	// menuitem.DefaultIsAvailable holds the default value on creation for the is_available field.
	menuitem.DefaultIsAvailable = menuitemDescIsAvailable.Default.(bool)
	// menuitemDescID is the schema descriptor for id field.
	menuitemDescID := menuitemFields[0].Descriptor()
	// menuitem.IDValidator is a validator for the "id" field. It is called by the builders before save.
	menuitem.IDValidator = menuitemDescID.Validators[0].(func(int64) error)
	modifierMixin := schema.Modifier{}.Mixin()
	modifierMixinFields0 := modifierMixin[0].Fields()
	_ = modifierMixinFields0
	modifierFields := schema.Modifier{}.Fields()
	_ = modifierFields
	// modifierDescUpdateTime is the schema descriptor for update_time field.
	modifierDescUpdateTime := modifierMixinFields0[0].Descriptor()
	// modifier.DefaultUpdateTime holds the default value on creation for the update_time field.
	modifier.DefaultUpdateTime = modifierDescUpdateTime.Default.(func() time.Time)
	// modifier.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	modifier.UpdateDefaultUpdateTime = modifierDescUpdateTime.UpdateDefault.(func() time.Time)
	// modifierDescName is the schema descriptor for name field.
	modifierDescName := modifierFields[1].Descriptor()
	// modifier.NameValidator is a validator for the "name" field. It is called by the builders before save.
	modifier.NameValidator = func() func(string) error {
		validators := modifierDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// modifierDescRequired is the schema descriptor for required field.
	modifierDescRequired := modifierFields[2].Descriptor()
	// modifier.DefaultRequired holds the default value on creation for the required field.
	modifier.DefaultRequired = modifierDescRequired.Default.(bool)
	// modifierDescMultiSelect is the schema descriptor for multi_select field.
	modifierDescMultiSelect := modifierFields[3].Descriptor()
	// modifier.DefaultMultiSelect holds the default value on creation for the multi_select field.
	modifier.DefaultMultiSelect = modifierDescMultiSelect.Default.(bool)
	// modifierDescMax is the schema descriptor for max field.
	modifierDescMax := modifierFields[4].Descriptor()
	// modifier.DefaultMax holds the default value on creation for the max field.
	modifier.DefaultMax = modifierDescMax.Default.(int)
	// modifier.MaxValidator is a validator for the "max" field. It is called by the builders before save.
	modifier.MaxValidator = modifierDescMax.Validators[0].(func(int) error)
	// modifierDescID is the schema descriptor for id field.
	modifierDescID := modifierFields[0].Descriptor()
	// modifier.DefaultID holds the default value on creation for the id field.
	modifier.DefaultID = modifierDescID.Default.(func() uuid.UUID)
	modifieroptionMixin := schema.ModifierOption{}.Mixin()
	modifieroptionMixinFields0 := modifieroptionMixin[0].Fields()
	_ = modifieroptionMixinFields0
	modifieroptionFields := schema.ModifierOption{}.Fields()
	_ = modifieroptionFields
	// modifieroptionDescUpdateTime is the schema descriptor for update_time field.
	modifieroptionDescUpdateTime := modifieroptionMixinFields0[0].Descriptor()
	// modifieroption.DefaultUpdateTime holds the default value on creation for the update_time field.
	modifieroption.DefaultUpdateTime = modifieroptionDescUpdateTime.Default.(func() time.Time)
	// modifieroption.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	modifieroption.UpdateDefaultUpdateTime = modifieroptionDescUpdateTime.UpdateDefault.(func() time.Time)
	// modifieroptionDescName is the schema descriptor for name field.
	modifieroptionDescName := modifieroptionFields[1].Descriptor()
	// modifieroption.NameValidator is a validator for the "name" field. It is called by the builders before save.
	modifieroption.NameValidator = func() func(string) error {
		validators := modifieroptionDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// modifieroptionDescPrice is the schema descriptor for price field.
	modifieroptionDescPrice := modifieroptionFields[2].Descriptor()
	// modifieroption.DefaultPrice holds the default value on creation for the price field.
	modifieroption.DefaultPrice = modifieroptionDescPrice.Default.(float64)
	// modifieroptionDescAvailable is the schema descriptor for available field.
	modifieroptionDescAvailable := modifieroptionFields[4].Descriptor()
	// modifieroption.DefaultAvailable holds the default value on creation for the available field.
	modifieroption.DefaultAvailable = modifieroptionDescAvailable.Default.(bool)
	// modifieroptionDescPreSelect is the schema descriptor for pre_select field.
	modifieroptionDescPreSelect := modifieroptionFields[5].Descriptor()
	// modifieroption.DefaultPreSelect holds the default value on creation for the pre_select field.
	modifieroption.DefaultPreSelect = modifieroptionDescPreSelect.Default.(bool)
	// modifieroptionDescID is the schema descriptor for id field.
	modifieroptionDescID := modifieroptionFields[0].Descriptor()
	// modifieroption.DefaultID holds the default value on creation for the id field.
	modifieroption.DefaultID = modifieroptionDescID.Default.(func() uuid.UUID)
	restaurantMixin := schema.Restaurant{}.Mixin()
	restaurantMixinFields0 := restaurantMixin[0].Fields()
	_ = restaurantMixinFields0
	restaurantFields := schema.Restaurant{}.Fields()
	_ = restaurantFields
	// restaurantDescUpdateTime is the schema descriptor for update_time field.
	restaurantDescUpdateTime := restaurantMixinFields0[0].Descriptor()
	// restaurant.DefaultUpdateTime holds the default value on creation for the update_time field.
	restaurant.DefaultUpdateTime = restaurantDescUpdateTime.Default.(func() time.Time)
	// restaurant.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	restaurant.UpdateDefaultUpdateTime = restaurantDescUpdateTime.UpdateDefault.(func() time.Time)
	// restaurantDescName is the schema descriptor for name field.
	restaurantDescName := restaurantFields[1].Descriptor()
	// restaurant.NameValidator is a validator for the "name" field. It is called by the builders before save.
	restaurant.NameValidator = restaurantDescName.Validators[0].(func(string) error)
	// restaurantDescPhone is the schema descriptor for phone field.
	restaurantDescPhone := restaurantFields[3].Descriptor()
	// restaurant.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	restaurant.PhoneValidator = restaurantDescPhone.Validators[0].(func(string) error)
	// restaurantDescEmail is the schema descriptor for email field.
	restaurantDescEmail := restaurantFields[4].Descriptor()
	// restaurant.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	restaurant.EmailValidator = restaurantDescEmail.Validators[0].(func(string) error)
	// restaurantDescAddress is the schema descriptor for address field.
	restaurantDescAddress := restaurantFields[5].Descriptor()
	// restaurant.AddressValidator is a validator for the "address" field. It is called by the builders before save.
	restaurant.AddressValidator = restaurantDescAddress.Validators[0].(func(string) error)
	// restaurantDescCity is the schema descriptor for city field.
	restaurantDescCity := restaurantFields[6].Descriptor()
	// restaurant.CityValidator is a validator for the "city" field. It is called by the builders before save.
	restaurant.CityValidator = restaurantDescCity.Validators[0].(func(string) error)
	// restaurantDescState is the schema descriptor for state field.
	restaurantDescState := restaurantFields[7].Descriptor()
	// restaurant.StateValidator is a validator for the "state" field. It is called by the builders before save.
	restaurant.StateValidator = restaurantDescState.Validators[0].(func(string) error)
	// restaurantDescZipCode is the schema descriptor for zip_code field.
	restaurantDescZipCode := restaurantFields[8].Descriptor()
	// restaurant.ZipCodeValidator is a validator for the "zip_code" field. It is called by the builders before save.
	restaurant.ZipCodeValidator = restaurantDescZipCode.Validators[0].(func(string) error)
	// restaurantDescCountry is the schema descriptor for country field.
	restaurantDescCountry := restaurantFields[9].Descriptor()
	// restaurant.CountryValidator is a validator for the "country" field. It is called by the builders before save.
	restaurant.CountryValidator = restaurantDescCountry.Validators[0].(func(string) error)
	// restaurantDescID is the schema descriptor for id field.
	restaurantDescID := restaurantFields[0].Descriptor()
	// restaurant.DefaultID holds the default value on creation for the id field.
	restaurant.DefaultID = restaurantDescID.Default.(func() uuid.UUID)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUpdateTime is the schema descriptor for update_time field.
	userDescUpdateTime := userMixinFields0[0].Descriptor()
	// user.DefaultUpdateTime holds the default value on creation for the update_time field.
	user.DefaultUpdateTime = userDescUpdateTime.Default.(func() time.Time)
	// user.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	user.UpdateDefaultUpdateTime = userDescUpdateTime.UpdateDefault.(func() time.Time)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = func() func(string) error {
		validators := userDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPhoneNumber is the schema descriptor for phone_number field.
	userDescPhoneNumber := userFields[3].Descriptor()
	// user.DefaultPhoneNumber holds the default value on creation for the phone_number field.
	user.DefaultPhoneNumber = userDescPhoneNumber.Default.(string)
	// userDescIsActive is the schema descriptor for is_active field.
	userDescIsActive := userFields[4].Descriptor()
	// user.DefaultIsActive holds the default value on creation for the is_active field.
	user.DefaultIsActive = userDescIsActive.Default.(bool)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[5].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
