// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Jiruu246/rms/internal/ent/category"
	"github.com/Jiruu246/rms/internal/ent/schema"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescName is the schema descriptor for name field.
	categoryDescName := categoryFields[1].Descriptor()
	// category.NameValidator is a validator for the "name" field. It is called by the builders before save.
	category.NameValidator = func() func(string) error {
		validators := categoryDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// categoryDescDescription is the schema descriptor for description field.
	categoryDescDescription := categoryFields[2].Descriptor()
	// category.DefaultDescription holds the default value on creation for the description field.
	category.DefaultDescription = categoryDescDescription.Default.(string)
	// category.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	category.DescriptionValidator = categoryDescDescription.Validators[0].(func(string) error)
	// categoryDescDisplayOrder is the schema descriptor for display_order field.
	categoryDescDisplayOrder := categoryFields[3].Descriptor()
	// category.DefaultDisplayOrder holds the default value on creation for the display_order field.
	category.DefaultDisplayOrder = categoryDescDisplayOrder.Default.(int)
	// category.DisplayOrderValidator is a validator for the "display_order" field. It is called by the builders before save.
	category.DisplayOrderValidator = categoryDescDisplayOrder.Validators[0].(func(int) error)
	// categoryDescIsActive is the schema descriptor for is_active field.
	categoryDescIsActive := categoryFields[4].Descriptor()
	// category.DefaultIsActive holds the default value on creation for the is_active field.
	category.DefaultIsActive = categoryDescIsActive.Default.(bool)
	// categoryDescCreatedAt is the schema descriptor for created_at field.
	categoryDescCreatedAt := categoryFields[5].Descriptor()
	// category.DefaultCreatedAt holds the default value on creation for the created_at field.
	category.DefaultCreatedAt = categoryDescCreatedAt.Default.(func() time.Time)
	// categoryDescID is the schema descriptor for id field.
	categoryDescID := categoryFields[0].Descriptor()
	// category.DefaultID holds the default value on creation for the id field.
	category.DefaultID = categoryDescID.Default.(func() uuid.UUID)
}
