// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Jiruu246/rms/internal/ent/predicate"
	"github.com/Jiruu246/rms/internal/ent/userauthprovider"
)

// UserAuthProviderUpdate is the builder for updating UserAuthProvider entities.
type UserAuthProviderUpdate struct {
	config
	hooks    []Hook
	mutation *UserAuthProviderMutation
}

// Where appends a list predicates to the UserAuthProviderUpdate builder.
func (_u *UserAuthProviderUpdate) Where(ps ...predicate.UserAuthProvider) *UserAuthProviderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *UserAuthProviderUpdate) SetUpdateTime(v time.Time) *UserAuthProviderUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *UserAuthProviderUpdate) SetProvider(v string) *UserAuthProviderUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *UserAuthProviderUpdate) SetNillableProvider(v *string) *UserAuthProviderUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetProviderUserID sets the "provider_user_id" field.
func (_u *UserAuthProviderUpdate) SetProviderUserID(v string) *UserAuthProviderUpdate {
	_u.mutation.SetProviderUserID(v)
	return _u
}

// SetNillableProviderUserID sets the "provider_user_id" field if the given value is not nil.
func (_u *UserAuthProviderUpdate) SetNillableProviderUserID(v *string) *UserAuthProviderUpdate {
	if v != nil {
		_u.SetProviderUserID(*v)
	}
	return _u
}

// Mutation returns the UserAuthProviderMutation object of the builder.
func (_u *UserAuthProviderUpdate) Mutation() *UserAuthProviderMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserAuthProviderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAuthProviderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserAuthProviderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAuthProviderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserAuthProviderUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := userauthprovider.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserAuthProviderUpdate) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := userauthprovider.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "UserAuthProvider.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderUserID(); ok {
		if err := userauthprovider.ProviderUserIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_user_id", err: fmt.Errorf(`ent: validator failed for field "UserAuthProvider.provider_user_id": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserAuthProvider.user"`)
	}
	return nil
}

func (_u *UserAuthProviderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userauthprovider.Table, userauthprovider.Columns, sqlgraph.NewFieldSpec(userauthprovider.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(userauthprovider.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(userauthprovider.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderUserID(); ok {
		_spec.SetField(userauthprovider.FieldProviderUserID, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userauthprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserAuthProviderUpdateOne is the builder for updating a single UserAuthProvider entity.
type UserAuthProviderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserAuthProviderMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *UserAuthProviderUpdateOne) SetUpdateTime(v time.Time) *UserAuthProviderUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *UserAuthProviderUpdateOne) SetProvider(v string) *UserAuthProviderUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *UserAuthProviderUpdateOne) SetNillableProvider(v *string) *UserAuthProviderUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetProviderUserID sets the "provider_user_id" field.
func (_u *UserAuthProviderUpdateOne) SetProviderUserID(v string) *UserAuthProviderUpdateOne {
	_u.mutation.SetProviderUserID(v)
	return _u
}

// SetNillableProviderUserID sets the "provider_user_id" field if the given value is not nil.
func (_u *UserAuthProviderUpdateOne) SetNillableProviderUserID(v *string) *UserAuthProviderUpdateOne {
	if v != nil {
		_u.SetProviderUserID(*v)
	}
	return _u
}

// Mutation returns the UserAuthProviderMutation object of the builder.
func (_u *UserAuthProviderUpdateOne) Mutation() *UserAuthProviderMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserAuthProviderUpdate builder.
func (_u *UserAuthProviderUpdateOne) Where(ps ...predicate.UserAuthProvider) *UserAuthProviderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserAuthProviderUpdateOne) Select(field string, fields ...string) *UserAuthProviderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserAuthProvider entity.
func (_u *UserAuthProviderUpdateOne) Save(ctx context.Context) (*UserAuthProvider, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAuthProviderUpdateOne) SaveX(ctx context.Context) *UserAuthProvider {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserAuthProviderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAuthProviderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserAuthProviderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := userauthprovider.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserAuthProviderUpdateOne) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := userauthprovider.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "UserAuthProvider.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderUserID(); ok {
		if err := userauthprovider.ProviderUserIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_user_id", err: fmt.Errorf(`ent: validator failed for field "UserAuthProvider.provider_user_id": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserAuthProvider.user"`)
	}
	return nil
}

func (_u *UserAuthProviderUpdateOne) sqlSave(ctx context.Context) (_node *UserAuthProvider, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userauthprovider.Table, userauthprovider.Columns, sqlgraph.NewFieldSpec(userauthprovider.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserAuthProvider.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userauthprovider.FieldID)
		for _, f := range fields {
			if !userauthprovider.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userauthprovider.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(userauthprovider.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(userauthprovider.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderUserID(); ok {
		_spec.SetField(userauthprovider.FieldProviderUserID, field.TypeString, value)
	}
	_node = &UserAuthProvider{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userauthprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
