// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// MenuItem is the predicate function for menuitem builders.
type MenuItem func(*sql.Selector)

// Modifier is the predicate function for modifier builders.
type Modifier func(*sql.Selector)

// ModifierOption is the predicate function for modifieroption builders.
type ModifierOption func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// OrderItem is the predicate function for orderitem builders.
type OrderItem func(*sql.Selector)

// OrderItemModifierOption is the predicate function for orderitemmodifieroption builders.
type OrderItemModifierOption func(*sql.Selector)

// RefreshToken is the predicate function for refreshtoken builders.
type RefreshToken func(*sql.Selector)

// Restaurant is the predicate function for restaurant builders.
type Restaurant func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserAuthProvider is the predicate function for userauthprovider builders.
type UserAuthProvider func(*sql.Selector)
