// Code generated by ent, DO NOT EDIT.

package mediaupload

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the mediaupload type in the database.
	Label = "media_upload"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldOwnerID holds the string denoting the owner_id field in the database.
	FieldOwnerID = "owner_id"
	// FieldPurpose holds the string denoting the purpose field in the database.
	FieldPurpose = "purpose"
	// FieldObjectKey holds the string denoting the object_key field in the database.
	FieldObjectKey = "object_key"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// EdgeAsset holds the string denoting the asset edge name in mutations.
	EdgeAsset = "asset"
	// Table holds the table name of the mediaupload in the database.
	Table = "media_uploads"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "media_uploads"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "owner_id"
	// AssetTable is the table that holds the asset relation/edge.
	AssetTable = "media_assets"
	// AssetInverseTable is the table name for the MediaAsset entity.
	// It exists in this package in order to avoid circular dependency with the "mediaasset" package.
	AssetInverseTable = "media_assets"
	// AssetColumn is the table column denoting the asset relation/edge.
	AssetColumn = "upload_id"
)

// Columns holds all SQL columns for mediaupload fields.
var Columns = []string{
	FieldID,
	FieldUpdateTime,
	FieldCreateTime,
	FieldOwnerID,
	FieldPurpose,
	FieldObjectKey,
	FieldStatus,
	FieldExpiresAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// ObjectKeyValidator is a validator for the "object_key" field. It is called by the builders before save.
	ObjectKeyValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Purpose defines the type for the "purpose" enum field.
type Purpose string

// Purpose values.
const (
	PurposeMenuItemImage        Purpose = "menu_item_image"
	PurposeRestaurantLogo       Purpose = "restaurant_logo"
	PurposeRestaurantCoverImage Purpose = "restaurant_cover_image"
)

func (pu Purpose) String() string {
	return string(pu)
}

// PurposeValidator is a validator for the "purpose" field enum values. It is called by the builders before save.
func PurposeValidator(pu Purpose) error {
	switch pu {
	case PurposeMenuItemImage, PurposeRestaurantLogo, PurposeRestaurantCoverImage:
		return nil
	default:
		return fmt.Errorf("mediaupload: invalid enum value for purpose field: %q", pu)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusIssued is the default value of the Status enum.
const DefaultStatus = StatusIssued

// Status values.
const (
	StatusIssued   Status = "issued"
	StatusConsumed Status = "consumed"
	StatusFailed   Status = "failed"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusIssued, StatusConsumed, StatusFailed:
		return nil
	default:
		return fmt.Errorf("mediaupload: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the MediaUpload queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByOwnerID orders the results by the owner_id field.
func ByOwnerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerID, opts...).ToFunc()
}

// ByPurpose orders the results by the purpose field.
func ByPurpose(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPurpose, opts...).ToFunc()
}

// ByObjectKey orders the results by the object_key field.
func ByObjectKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldObjectKey, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByOwnerField orders the results by owner field.
func ByOwnerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnerStep(), sql.OrderByField(field, opts...))
	}
}

// ByAssetField orders the results by asset field.
func ByAssetField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAssetStep(), sql.OrderByField(field, opts...))
	}
}
func newOwnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
	)
}
func newAssetStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AssetInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, AssetTable, AssetColumn),
	)
}
