// Code generated by ent, DO NOT EDIT.

package orderitemmodifieroption

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the orderitemmodifieroption type in the database.
	Label = "order_item_modifier_option"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrderItemID holds the string denoting the order_item_id field in the database.
	FieldOrderItemID = "order_item_id"
	// FieldModifierOptionID holds the string denoting the modifier_option_id field in the database.
	FieldModifierOptionID = "modifier_option_id"
	// FieldQuantity holds the string denoting the quantity field in the database.
	FieldQuantity = "quantity"
	// FieldOptionName holds the string denoting the option_name field in the database.
	FieldOptionName = "option_name"
	// FieldOptionPrice holds the string denoting the option_price field in the database.
	FieldOptionPrice = "option_price"
	// EdgeOrderItem holds the string denoting the order_item edge name in mutations.
	EdgeOrderItem = "order_item"
	// EdgeModifierOption holds the string denoting the modifier_option edge name in mutations.
	EdgeModifierOption = "modifier_option"
	// Table holds the table name of the orderitemmodifieroption in the database.
	Table = "order_item_modifier_options"
	// OrderItemTable is the table that holds the order_item relation/edge.
	OrderItemTable = "order_item_modifier_options"
	// OrderItemInverseTable is the table name for the OrderItem entity.
	// It exists in this package in order to avoid circular dependency with the "orderitem" package.
	OrderItemInverseTable = "order_items"
	// OrderItemColumn is the table column denoting the order_item relation/edge.
	OrderItemColumn = "order_item_id"
	// ModifierOptionTable is the table that holds the modifier_option relation/edge.
	ModifierOptionTable = "order_item_modifier_options"
	// ModifierOptionInverseTable is the table name for the ModifierOption entity.
	// It exists in this package in order to avoid circular dependency with the "modifieroption" package.
	ModifierOptionInverseTable = "modifier_options"
	// ModifierOptionColumn is the table column denoting the modifier_option relation/edge.
	ModifierOptionColumn = "modifier_option_id"
)

// Columns holds all SQL columns for orderitemmodifieroption fields.
var Columns = []string{
	FieldID,
	FieldOrderItemID,
	FieldModifierOptionID,
	FieldQuantity,
	FieldOptionName,
	FieldOptionPrice,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultQuantity holds the default value on creation for the "quantity" field.
	DefaultQuantity int
	// QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	QuantityValidator func(int) error
	// OptionNameValidator is a validator for the "option_name" field. It is called by the builders before save.
	OptionNameValidator func(string) error
)

// OrderOption defines the ordering options for the OrderItemModifierOption queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOrderItemID orders the results by the order_item_id field.
func ByOrderItemID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderItemID, opts...).ToFunc()
}

// ByModifierOptionID orders the results by the modifier_option_id field.
func ByModifierOptionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModifierOptionID, opts...).ToFunc()
}

// ByQuantity orders the results by the quantity field.
func ByQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantity, opts...).ToFunc()
}

// ByOptionName orders the results by the option_name field.
func ByOptionName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOptionName, opts...).ToFunc()
}

// ByOptionPrice orders the results by the option_price field.
func ByOptionPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOptionPrice, opts...).ToFunc()
}

// ByOrderItemField orders the results by order_item field.
func ByOrderItemField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrderItemStep(), sql.OrderByField(field, opts...))
	}
}

// ByModifierOptionField orders the results by modifier_option field.
func ByModifierOptionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newModifierOptionStep(), sql.OrderByField(field, opts...))
	}
}
func newOrderItemStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OrderItemInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OrderItemTable, OrderItemColumn),
	)
}
func newModifierOptionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ModifierOptionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ModifierOptionTable, ModifierOptionColumn),
	)
}
